### ISSUE TITLE
Add "HIT Facilititors Present" to IV Contacts forms

### ISSUE THREAD

**Issue by seemack** [seemack/healthy-hearts-northwest-dev#100]
Caitlin mentioned that her HIT team would appreciate this.  She'd envisioned something similar to the Clinic Personnel boxes, where you click off whoever's present.  I suggested that while that's certainly do-able, it would take some time to do and therefore be harder to prioritize.  Adding a text box (probably for ORPRN only) labeled "Facilitators Present" would be super easy though, and seemed good enough for her purposes.

**Comment by kuoxes1** [comment]
Chris will add a textbox and be aware that she might actually want this added to a report down the line.

**Comment by seemack** [comment]
Added to IVContacts.  Ready for testing in dev.
