### ISSUE TITLE
Add Search Parameters to Qual Export

### ISSUE THREAD

**Issue by seemack** [seemack/healthy-hearts-northwest-dev#101]
Clarissa would like to filter the download based on
- date
- site (ORPRN/Qualis)
- clinic
- coach

This will require a new filter & download page to generate these parameters.  Let's talk about priority.
I'm adding this issue so I can close the general Qual Export request - issue #51 .

**Comment by squabwrangler** [comment]
Clarissa thinks we will need this feature in November.

**Comment by seemack** [comment]
Plan to start with date parameters. Add other parameters after.

**Comment by squabwrangler** [comment]
Per Clarissa today, we only need parameters for date and practice now.  Thanks!!

**Comment by seemack** [comment]
Export has been failing. Prioritize this request.

**Comment by seemack** [comment]
Date parameters are enabled in dev. Planning to shift to other qualitative export features before returning to these parameters.

**Comment by squabwrangler** [comment]
Priority for searching

1. Date range (completed)
2. Practice/clinic
3. Coach
4. Site

**Comment by squabwrangler** [comment]
Looks good to me!
