### ISSUE TITLE
visit fixes needed

### ISSUE THREAD

**Issue by squabwrangler** [seemack/healthy-hearts-northwest-dev#104]
See emails from Tara Kline, 6/27/16
Carolyn B. 6/27/16
Caitlin 6/24/16

**Comment by seemack** [comment]
Hmm, maybe each fix *should* get its own separate Github issue after all.  I've made the fixes I see in my email, but I don't see the dates associated with the above emails. Maybe they're packaged with other emails that have different dates?

I've probably made these fixes already, but just in case:  could someone help me track down these requests?

**Comment by seemack** [comment]
Tara K./Carolyn B. emails from 6/28 are definitely taken care of - several in-person visits didn't have their in-person visit number assigned. This can happen if a visit is defined as a different sort, then after saving, it's redefined as "required in-person visit (5)."

Unless this happens a lot, I suggest we continue to fix them by hand.

**Comment by squabwrangler** [comment]
How do I search by DB ID?

**Comment by squabwrangler** [comment]
Looks good, rather than push to production, should this just be closed?

**Comment by seemack** [comment]
I'm going to close this because it should be fixed by the Exclamation Point bug fix.  If we need to re-open other errors that derive from those changes, let's do that separately.
