### ISSUE TITLE
practice id issues in DB

### ISSUE THREAD

**Issue by kuoxes1** [seemack/healthy-hearts-northwest-dev#105]
in ivcontacts export I see these practiceIDS for these two practices:
21408  HF
21410  GS

In practices Export I see this:
21204  HF
21205  GS

In our survey trackers, and for randomization we used the practices export to get IDS so those are the "right" ones for me, but I don't know how that could change for IV contacts.  i've double checked all the others and they match from our 210 list.

**Comment by seemack** [comment]
I may need help with this one.  When I export, I see HF having practice_id 21408 only, in both Practices and IVContacts.  Same deal with GS - I see 21410 in both exports.  I don't see 21204 or 21205 being used anywhere in the system right now.

It's possible that if the practice_id is reset, the two files could be out of sync until they're both regenerated.  Could that have happened here?

**Comment by seemack** [comment]
I think I got this.  The caching algorithm is assigning a new ID each time an activity is marked "PAL returned," even if the PAL had already been returned and an ID assigned.  I've fixed this for the future.

5 practices appear to have had their IDs changed, though it's possible there are a few more.  Their database IDs (the number you see in the URL bar), abbreviation name & assigned IDs are
17370 GSMG (21410)
17778 SMC (21083)
18323 OBMC (32377)
17387 HFM (21408)
18327 NC (32375)

I can change these manually.

**Comment by seemack** [comment]
I wrote a script that looks for any change in assigned IDs.  I found the changes below.  We'll have to ensure that the most recent ID is being used for everything moving forward, or I'll have to fix the ID.

21110 <- 21104
32329 <- 32293 <- 32235 <- 32234 <- 32232
12397 <- 12396 <- 12395 <- 12394 <- 12393
21226 <- 21155
21228 <- 21187
21388 <- 21387
12287 <- 12286 <- 12285 <- 12284 <- 12017
32310 <- 32309
32276 <- 32237 <- 32034
32346 <- 32345 <- 32336 <- 32335 <- 32330 <- 32313
32348 <- 32347 <- 32334 <- 32333 <- 32331 <- 32314
12152 <- 12010
12149 <- 12039
12173 <- 12165 <- 12143 <- 12014
21181 <- 21180 <- 21179 <- 21178 <- 21177
32355 <- 32354 <- 32353 <- 32324 <- 32264
32374 <- 32373 <- 32356 <- 32292 <- 32263
32304 <- 32269
32300 <- 32172 <- 32100
12198 <- 12018
21094 <- 21093
21225 <- 21157
21091 <- 21090
21148 <- 21147 <- 21122
21132 <- 21131
21212 <- 21211 <- 21206
21214 <- 21213 <- 21209 <- 21208 <- 21207
21109 <- 21108
32291 <- 32170 <- 32099
32344 <- 32343 <- 32342 <- 32317
32350 <- 32349 <- 32341 <- 32340 <- 32339 <- 32316
21224 <- 21156
32229 <- 32144
21410 <- 21409 <- 21204
32296 <- 32295 <- 32194
32328 <- 32265
21227 <- 21154 <- 21153
21203 <- 21202 <- 21201 <- 21200
21129 <- 21128
32283 <- 32079
32371 <- 32327 <- 32326 <- 32305 <- 32294 <- 32270
32370 <- 32358 <- 32357 <- 32323
32236 <- 32197
32241 <- 32240 <- 32037
32261 <- 32260 <- 32259
32302 <- 32196
21082 <- 21081 <- 21080
32380 <- 32378
32377 <- 32376 <- 32303 <- 32233
21086 <- 21013
21088 <- 21087
21089 <- 21085
32372 <- 32352 <- 32351 <- 32338 <- 32337 <- 32332 <- 32315
32141 <- 32031
12239 <- 12174
12151 <- 12150 <- 12038
21408 <- 21407 <- 21205
32369 <- 32360
32299 <- 32298 <- 32297 <- 32103 <- 32102
32231 <- 32019
32375 <- 32306 <- 32267 <- 32266
32230 <- 32145
12193 <- 12192 <- 12191 <- 12190 <- 12041
32140 <- 32139 <- 32077
32189 <- 32188
32301 <- 32171 <- 32101
12184 <- 12183 <- 12006
21117 <- 21116
21411 <- 21364

**Comment by kuoxes1** [comment]
Only two need updating ASAP!
17387 HFM (21408) should be 21205 everywhere please change!
17370 GSMG (21410) - should be 21204 everywhere please change!

Many the change happened really early on and everything matches.:
17778 SMC (21083)  should be 21083 - change must have been early on, keep as is!
12184 should be 12184 change must have been early on, keep as is.

Many that were just not enrolled:
18323 OBMC (32377) not in final dataset can ignore
18327 NC (32375) not in final dataset can ignore!

**Comment by seemack** [comment]
Changes made. I'm marking this "ready for testing" - let me know when we should close this since it's already in production.
