### ISSUE TITLE
Add a missed visit "touch" documentation

### ISSUE THREAD

**Issue by kuoxes1** [seemack/healthy-hearts-northwest-dev#106]
1.  this would be added into other required contacts= (in person) and (phone/web)
2.    if those are elected, allow "this visit was cancelled" check box to show up.
3.  If that checkbox is checked, then pop up"
Reason missed (coach issue/clinic issue)        
Number of attempts made by coach to schedule
comments field

4. if check box is checked, we want to disable the redflagging mechanism for this visit

**Comment by squabwrangler** [comment]
Does this need to be in any of the exports or displays?

**Comment by seemack** [comment]
This is part of a bundle I'd like to push out to production (along with a couple other issues).  Can we test this in the next couple days so I can push everything?

If we need to add these fields to exports or displays, we can add those requests as separate issues.
