### ISSUE TITLE
Delete ! from the coach landing page

### ISSUE THREAD

**Issue by kuoxes1** [seemack/healthy-hearts-northwest-dev#107]
Nicole will ask them to stop putting  "none" in  after second quarterly in person visit
Chris will take away ! on coach landing page so they might have less anxiety about it.

**Comment by kuoxes1** [comment]
Chris will double check - we don't see any flags at all even in the practice view- but none on the coach landing page which is great

**Comment by seemack** [comment]
Working fine - there are just very few visits that haven't been cleaned up by now.
