### ISSUE TITLE
PDSA export

### ISSUE THREAD

**Issue by squabwrangler** [seemack/healthy-hearts-northwest-dev#109]
From Ross 7/13/2016:

Just wanted to check in and about a couple IV tracker requests we are hoping to see in the near future.  
•	Fixing an issue where a quarterly visit cannot be changed from a Q1 to a Q2 visit if it was saved incorrectly as a Q1 at first. This is a pretty widespread issue and is interfering with our count of Q2 visits. 
•	Could we get an export out on an ongoing basis that shows PDSA entries by clinic, description, status, and whether it was adopted, adapted, or abandoned?

These changes are pretty critical to our ongoing monitoring of clinic progress and will save us time that would otherwise be spent manually auditing the database.

**Comment by kuoxes1** [comment]
make a new PDSA export (don't add to IV contacts)

**Comment by seemack** [comment]
Pushed to Dev.  You can find it in the "Manager Area."  If this and Issue #106 can both get tested, I can push them out with the other package of updates.

**Comment by kuoxes1** [comment]
Looks great ready for production:  
Then need to tell coach managers it's there.
Double checked that ORPRN/QUALIS each can only see their practices - looks great!
