### ISSUE TITLE
staff update

### ISSUE THREAD

**Issue by kuoxes1** [seemack/healthy-hearts-northwest-dev#111]
**In ivcontact staff section:**
Add a button that opens up a new window that displays the recruitment staff page
Add the H2N role next to names that display
Remove the "add staff member" link
(be aware of the issue of reloading/updating a page and having new info update)

**in recruitment staff page:**
DELETE 
all types of H2N contacts except primary site contact 
ADD
Primary site contact HOVER recruitment, payments, Practice Survey, etc
Staff survey contact 
ABCS survey contact 
Learning emails contact  HOVER webinars, SOL, etc,

**Comment by kuoxes1** [comment]
These are checkboxes, just to be clear!  Just like currently displayed in recruitment contacts.

**Comment by seemack** [comment]
We'd been talking about a pop-up on the IVContacts page.  Is there a reason it should be there instead of having its own link on the Coach Practice starting page?  That would save (a lot!) of time in building the behind-the-scenes data feed that the IVContacts "add staff member" uses.

**Comment by seemack** [comment]
After talking to Elena, we're going to simplify this a bit.  We'll keep all staff edits in the Staff Edit section in Recruitment - which will be changed to reflect the new contact types - but I'll add a link in the Coach Practice page that will allow users to navigate directly there.  I'll also note in the IVContact page that staff cannot be edited within the contact, and provide instructions on navigating to the Staff Edit area.

**Comment by seemack** [comment]
Super easy question:  are we also removing the section of "EHR Duties"?

**Comment by seemack** [comment]
Another question: Right now, updating a Practice in the Recruitment section (where the Staff List is) redirects the user to the full recruitment-side Practices list.  Do we want to redirect to the Coach Practice page instead?  Is there anyone (maybe still doing recruitment) who wants to go to the Practices list, and would freak out by being redirected somewhere else?

**Comment by seemack** [comment]
Remove EHR duties, too

**Comment by seemack** [comment]
We're still talking about where to redirect users after updating staff information:  to the Recruiter Practices page or to the Coach Practice page.

**Comment by seemack** [comment]
Otherwise ready for testing.

**Comment by seemack** [comment]
We decided to return to the Practices (recruitment-side) page.  Coaches can easily enough hit the "Coach Area" button to get back to their practices.  Data entry people will benefit from returning to the Practices page.

**Comment by squabwrangler** [comment]
I just spoke with Caitlin and Katrina about this feature, they think it would be best if the redirect was to the coach landing page (this will be easier for coaches and they themselves think they will use the back button to access their coaches pages/or the coach list which is how they would access them normally).  They also think it might be handy to have a text box below the check boxes in the Staff section to be able to include the dates each were updated.  They also asked if there is anyway to upload the contacts from the document library thus cutting down the data entry time for these.

**Comment by squabwrangler** [comment]
In our last database meeting, Chris mentioned that it is fairly easy to display the date that something was updated, should we add this to each H2N staff checkbox so that people know when this was last updated? I do not see a downside to this. Others?

**Comment by kuoxes1** [comment]
Primary contact (general emails, data payments, Practice Survey)
Staff Survey
ABCS Survey
Learning Emails (SOL, Webinars)

**Comment by kuoxes1** [comment]
make sure the personnel export gets updated with the final staff contact roles - thanks!

**Comment by kuoxes1** [comment]
DONE!! thanks!
