### ISSUE TITLE
Qualitative export sometime missing GYR flag

### ISSUE THREAD

**Issue by seemack** [seemack/healthy-hearts-northwest-dev#112]
Per Erika:
"Something odd is happening when I export qual data, occasionally the GYR rating does not pull into the reports.  I have not found a reason for this.  
Attached is an example of one that is not pulling the rating in even though it appears in the database for this visit."

The example is an SB contact ID 12262, 4/26/2016.  GYR color is blank.

**Comment by seemack** [comment]
Fixed, certainly that practice & visit are fixed.  Let me know if there's anything else oddly missing.

**Comment by squabwrangler** [comment]
It looks good in dev.
