### ISSUE TITLE
PDSA delete feature request

### ISSUE THREAD

**Issue by squabwrangler** [seemack/healthy-hearts-northwest-dev#115]
From Beth:  If there’s a way to include a “delete” for blank PDSAs, that would be awesome. But in any case, I wanted to let you know about this issue.

Caitlin response: Our PERCs had a very strong response to this update...They definitely don't want anyone to delete their entries (even if it seems like PDSA cycle information shouldn't be carried forward/shouldn't be included in some entries). They would love the chance to delete/edit items themselves, but feel uncomfortable with others deleting their entries.

**Comment by seemack** [comment]
I was thinking about doing this, too - deleting any PDSAs that are blank all across (no description, status or comment).  Some of those saved improperly in the early days of the database.

And maybe delete the PDSAs marked as "none"?  But I think those are folks trying to avoid the red exclamation marks, and I'd hate for a "fix" to just get everyone upset again.

**Comment by squabwrangler** [comment]
Nicole signed off on this plan in the db meeting, 7/27/16
