### ISSUE TITLE
extra PDSA cycles deleting

### ISSUE THREAD

**Issue by squabwrangler** [seemack/healthy-hearts-northwest-dev#116]
Nicole signed off on Chris deleting the extra PDSA cycles that were associated with HIT visits and ad hoc visits.

**Comment by seemack** [comment]
87 records deleted this morning.  I made a full database backup and extracted the rows being deleted into a CSV file on the 1 in a billion chance we ever need this stuff.

**Comment by seemack** [comment]
Closing - I'm not sure what "ready for testing" would mean in this context.
