### ISSUE TITLE
Add missed touch data to IVcontacts and Qualitative export

### ISSUE THREAD

**Issue by kuoxes1** [seemack/healthy-hearts-northwest-dev#117]
add all fields.

we love you chris!!!

Reference issue #106

**Comment by seemack** [comment]
Added to IV Contacts export.

The qualitative export was already exporting comments - nothing to add there.

**Comment by squabwrangler** [comment]
The qual. export seems to pull PDSA data from future visits (I went in to Hearts Practice and entered a date, 8/3, that was cancelled before the most recent date, 9/9 and it does not indicate that the visit was cancelled in the export. That might be ok, but the PDSA thing is weird.

**Comment by kuoxes1** [comment]
Add cancellation date to the qualitative export, and don't have to deal with this PDSA forwarding glitch - we can ignore it! (CUE DANCE PARTY MUSIC!)

**Comment by seemack** [comment]
I may need some hand holding on this one.  I'm not sure what the future PDSAs refer to.  If the data is there, it will pull, even if the dates are in the future.  Cancellations aren't taken into account, though they could be.  Maybe someone could walk me through this?

There's no cancellation date per se - but there's a date associated with the visit, whether the "visit" was a cancellation or a real visit.  I could include "cancelled yes/no" to the Qualitative Export.  Or just pull non-cancelled visits.

**Comment by kuoxes1** [comment]
???????  dance party on hold ????????
out of order data means that PDSA forwarding won't work properly - this is more of a training issue/reminder to coaches to enter data linearly - Ask Nicole to remind coaches at call Thurs or Mon

**Comment by squabwrangler** [comment]
I have asked Nicole to remind coaches to enter data chronologically.
