### ISSUE TITLE
Exclamation point mystery

### ISSUE THREAD

**Issue by squabwrangler** [seemack/healthy-hearts-northwest-dev#118]
From: Shauna Banner 
Sent: Wednesday, August 03, 2016 1:06 PM
To: Carolyn Brill
Subject: Can you take a look at Physician's Medical Center?

I documented yesterday’s visit and there is a red exclamation next to it and for the life of me, I can’t see what I missed?  It is the 8/2 visit.

**Comment by seemack** [comment]
This is clearly a bug. The exclamation point is showing up because there's no QICA.  (And there shouldn't be, but bear with me.)

Right now, the QICA only shows up for in-person visits 1 & 4.  But the "missing_data" function is looking for QICA values at other visits.  Just reassure me and I'll make this change: QICA can only be considered "missing" on in-person visits 1 & 4.  At all other times, it's okay to be missing.  Right?

**Comment by seemack** [comment]
OK to be missing for other visits.  In-person visit 1 & 4 only.

**Comment by seemack** [comment]
It looks like the problem visit was initially called "quarterly in-person" - and so was assigned in-person visit 4, where a QICA was expected - and later was redefined to "other required contact."  I've removed the in-person visit number from that record.

**Comment by squabwrangler** [comment]
Shauna sent an email 8/26/2016 that Cascade Medical has the same issue, wondering if this is the same problem? Going forward, will we just fix these manually? If so, I think we can close this issue.

**Comment by squabwrangler** [comment]
Looks like this is still happening:  I tested in PDSA clinic, changed what should have been required visit #4 to other required monthly contact and got the red !

**Comment by seemack** [comment]
Can you tell me which record this is so I can look into it?

**Comment by squabwrangler** [comment]
8/18/2016 for PDSA clinic, me as coach.

**Comment by seemack** [comment]
Thanks Erika.  Instead of just fixing the display, I rewrote the "which of the 5 required visits is this one?"  logic.

I believe it's all working now.

**Comment by squabwrangler** [comment]
One more issue with the exclamation mark that I just discovered in dev:  the tiering tool for capacity is locked, I am unable to enter anything beyond Baseline. See my "Test practice" in dev for required visit 2 and 3.

**Comment by kuoxes1** [comment]
After this is pushed to production need to loop back to these issues and make sure they were actually resolved in production
