### ISSUE TITLE
this is an issue

### ISSUE THREAD

**Issue by rpardee** [seemack/healthy-hearts-northwest-dev#12]
Won't someone do something about how much weight I gained over Christmas?

**Comment by seemack** [comment]
Hmm, the only additional thing I'd like to see is separate checkoffs for us as developers & the rest of the crew as testers.  Would issues remain open until they're tested by the team? Could we do this using labels? Or would we keep a shadow copy of issues for "final checkoff"?  (If there's an issues export feature, the latter would be less heinous.)

**Comment by rpardee** [comment]
That would be nice I agree.  Probably labels could work, though it might be clunky.

If users can re-open issues that we've closed as a method of disagreeing that something is fixed, would that serve?  I think they can.  If you want to close this guy as a test I'll see if I can re-open.

**Comment by seemack** [comment]
Weight gain solved:  switching from heavy holiday beers to Bud Light Lime-a-ritas.  Issue closed.

**Comment by rpardee** [comment]
Dang--can't re-open.  Looks like [these are the rules](https://stackoverflow.com/questions/21333654/how-to-re-open-an-issue-in-github):

> Github has very simple rights/privileges (and even simpler management for them).
> 
> If you are not a collaborator of a repo, then (in regards to issues)
> 
> * you can open issues
> * you can comment on all existing issues (open or closed)
> * you can close your own issues
> * you can re-open your own issues *if you closed them yourself
> * you cannot close or re-open issues opened by someone else
> * you cannot re-open your own issues if a repo collaborator closed them

**Comment by rpardee** [comment]
Also--bud lite?  HOW DARE YOU!!

**Comment by seemack** [comment]
I've added you as a collaborator - were you not before? doesn't look like it.  Can you imagine any problems with providing collaborator access to our colleagues?

Do I get more credibility if I name check OE800 or Coqui 900 or some other beer I know from 1980s rap albums?  Do the kids still call them albums?

**Comment by rpardee** [comment]
Let's just go with Colt 45 Malt Liquor, because it puts me in mind of that dope-ass Lando Kardashian from the star wars.

I don't think I was a collaborator--I think that gives me permission to directly push to the repo, which you may or may not want.

**Comment by seemack** [comment]
Closed cuz we wuz just havin fun.
