### ISSUE TITLE
DB not populating tiering capacity correctly

### ISSUE THREAD

**Issue by squabwrangler** [seemack/healthy-hearts-northwest-dev#122]
Example of quarterly visit not pulling through. Even though I can label it as a “quarterly visit” I can’t change the tiering capacity- it is as if it is not truly a quarterly visit.  This also may be why the exclamation mark exists?
 
From the detail of the 6/9/16/visit
 
Sand point Family Medicine and Urgent care  coach: tara kline

**Comment by squabwrangler** [comment]
Same issue with Tara's 2016-06-14 visit in Christ clinic

**Comment by seemack** [comment]
Very likely this is tied to the Exclamation Mark bug.  Let's see if we can sign off on the Ready for Testing issues, push them into production, and see if it goes away.

**Comment by seemack** [comment]
Forwarding this information from Erika in the Exclamation Point Bug issue #118 .

"One more issue with the exclamation mark that I just discovered in dev:  the tiering tool for capacity is locked, I am unable to enter anything beyond Baseline. See my "Test practice" in dev for required visit 2 and 3."

**Comment by kuoxes1** [comment]
Deschutes Rim Clinic  Emily Chirnside is the coach: 
This Q2 visit didn't populate in the table: check after you push exclamation point to production
Also check if the tiering tool V2 has data for the visit for this practice?  If not... (CUE OMINOUS MUSIC)

**Comment by seemack** [comment]
Remnants of the Specific Visit Number bug.  The view is pulling the @contact_specific variable rather than an actual field.  Think about how to allow this for new & update.

**Comment by kuoxes1** [comment]
Erika follow-up with Emily and then if problem solved close this issue.

**Comment by kuoxes1** [comment]
CASE CLOSED!!!! (dance party)  Nicole will message to Caitlin/Ross at coach managers call.
