### ISSUE TITLE
Learning Emails (SOL, webinars) change label

### ISSUE THREAD

**Issue by kuoxes1** [seemack/healthy-hearts-northwest-dev#125]
Change the label in the contacts checkboxes to be something else... which Erika will determine after Thursday.
(EOL, webinars, educational outreach?)

**Comment by seemack** [comment]
Quick check:  do we have preferred labels for these?

**Comment by squabwrangler** [comment]
Please label this "Shared opportunities for learning webinar/office hour series"

**Comment by squabwrangler** [comment]
looks good

**Comment by seemack** [comment]
In production.
