### ISSUE TITLE
Info in data entry is not showing up in exports

### ISSUE THREAD

**Issue by ltuz** [seemack/healthy-hearts-northwest-dev#127]
When a topic is entered as “not discussed” and HIT Tiering/EHR don’t show up in export  - Caitlin needs this info for their 65% QA review (ask Nicole if questions)

**Comment by squabwrangler** [comment]
This relates to the HLC's, apparently "not discussed" is not showing up in the export.

**Comment by seemack** [comment]
Note to programmer:  ivcontact_milestone_*_progress variables have a value of 9 not included in the PROGRESS_VALS definition in ivcontact.rb to allow "did not discuss" to be broken out separately from the other values. 9s are not exporting as blanks. I'll add a PROGRESS_EXPORT_VALS definition which allows the 9s to be displayed as "Did not discuss" but doesn't get called when the radio buttons are created.

**Comment by seemack** [comment]
EHR Vendor (hit_vendor) and HIT Tier also not on current export. Adding.

**Comment by squabwrangler** [comment]
looks good to me.
