### ISSUE TITLE
PDSA's need forwarding

### ISSUE THREAD

**Issue by squabwrangler** [seemack/healthy-hearts-northwest-dev#128]
Hi Erika,

Looks like the PDSAs for Family Medical Group NE are still not pulling forward. Visit #5 was the last one in which they appear. Can you help get the PDSAs moved forward so they show up in visit 6 and 7? The dates are as follows:

•	Visit 5: 6/7/2016
•	Visit 6: 8/2/2016
•	Visit 7: 9/14/2016

Please let me know if there is anything else you need from me to make this happen.

Thanks!
Beth

**Comment by seemack** [comment]
A HIT visit in the middle disrupted this, based on the old algorithms.  I manually associated those PDSAs with the later visits, and they're forwarding properly.

I'm not sure how to mark this - the only way to make the fix was by doing it in production.
