### ISSUE TITLE
Staff export exclusions

### ISSUE THREAD

**Issue by squabwrangler** [seemack/healthy-hearts-northwest-dev#129]
For the staff export, can we limit this to include only active enrolled practices, please?

**Comment by kuoxes1** [comment]
Chris this is a high priority for us since our colleagues want to do a data pull next Wednesday.  Either restrict OR add a column that tells what the current status is if that's easier so we can sort.  THANK YOU!!

**Comment by seemack** [comment]
What's our definition for "active enrolled practices"?  Would status="Interested & Eligible" (from Recruitment) and dropped="no" work?  Is there anything else we need to look at?

**Comment by kuoxes1** [comment]
In the practices export there is a variable called "active in project?"  with a true false in the export.  Whatever feeds into that is correct.  It pulls people who signed a pal and have an ID, and has "false" for anyone who is currently dropped.  That's the one to use!!  But I'm not sure what it is within the database itself.

**Comment by seemack** [comment]
The "active in project" defaults to true, but gets flipped to false when a practice drops out.  I'll include this variable in the staff export.

**Comment by squabwrangler** [comment]
Kilian and I found a potential issue with this export:
Pendleton Primary Care used to be a dropped clinic, they re-entered 3/22/16, but the DB practice export still says “ false” for active in project. Can we make it so if you enter a re-enter date that “active in project” changes to “true?”

Also, the Curry Medical Practices are really dropped, but they have a re-enter date, this is strange.

**Comment by seemack** [comment]
I think both these problems go back to when the re-entry date was populating all the time, even when it wasn't supposed to.  I've fixed the data in the back end and don't expect errors in future.  If you find more errors from when things weren't working right, let me know and I'll fix those, too.

**Comment by kuoxes1** [comment]
I don't see any more issues - is this ready to close?
