### ISSUE TITLE
Remove Status from Coach section

### ISSUE THREAD

**Issue by seemack** [seemack/healthy-hearts-northwest-dev#13]
The original idea was to use a short bit of text to communicate with managers. The need and use for this was not clear to any coaches, and we never developed a reasonable implementation strategy.

So let's delete Status from anywhere it's currently showing up (Coach Practice Page + Coach Notes at minimum).

**Comment by seemack** [comment]
Remove status from displays.  Remove "brief status update" from "New Item" on Coach Practice overview.

**Comment by seemack** [comment]
Honestly, I'm not sure how to test this - how to test for an absence. I'm assuming that after folks have used it a bit and haven't come across a reference to that "Brief Status" field, we should be able to close this.

**Comment by vanborkulo** [comment]
I am still seeing  'status' on the bar on coach view landing page.  And, in new action item 'brief status update' is still an option.

**Comment by vanborkulo** [comment]
"Brief Status update' is gone from the drop down, but 'status' is still in the bar on the coach landing page.

**Comment by seemack** [comment]
Removed status column from app\views\coach_practices\list.html.erb

**Comment by squabwrangler** [comment]
looks good! Ok to close.
