### ISSUE TITLE
add visit cancelled for Quarterly in person visits

### ISSUE THREAD

**Issue by squabwrangler** [seemack/healthy-hearts-northwest-dev#130]
One of our PERCs was wondering if we could put a “Visit Canceled” check box under the “Quarterly in-person visit” form – like there is for the “Other required monthly contact (in-person)” and “Other required monthly contact (phone/web)” forms.
Thanks for your consideration 
Best,
Caitlin

**Comment by kuoxes1** [comment]
Another high priority one though not as urgent as the staff export.  THANKS!!

**Comment by seemack** [comment]
I can definitely add this but just want to make sure:  do we want coaches to be able to cancel one of the 5 quarterly visits?  If that's a yes, I can roll this out quickly.

**Comment by vanborkulo** [comment]
Yes, okay to have them miss BUT they will need to have a comment box to explain the reason. I will also give them some instruction on appropriate use.

**Comment by kuoxes1** [comment]
The idea is that some wend dark and they want to document that a whole visit was scheduled and missed rather than continue to have it flagged... but I agree a text box is needed too!

**Comment by seemack** [comment]
Added.
