### ISSUE TITLE
Q1 and Q4 QICA tables display on landing page

### ISSUE THREAD

**Issue by squabwrangler** [seemack/healthy-hearts-northwest-dev#131]
I documented my first Q4 QICA today and am wondering if there is a way I can view the initial QICA results with the most recent for comparison.  The second entry is the only one that displays and I’m wondering if I’m missing a step or something to get them both to display.  If not, is this something that can be considered to add to our clinic landing page?

Thanks,
David

**Comment by squabwrangler** [comment]
Chris will ask Nicole for clarification and for priority level. He will include the other coach asks as well.

**Comment by squabwrangler** [comment]
Elena to add this item to survey for coaches.

**Comment by squabwrangler** [comment]
From Ross: Thanks Erika, I appreciate the status check. This is something the coaches are getting restless about and it helps to be able to let them know it's on your list.  I think the most quick and efficient way to show it is just to put both tables (one for QICA 1 and one for QICA 2) side by side in the place they are currently. It looks like there is sufficient space in the clinic landing page to put both above the PDSA list. Alternatively, just having clearly delineated separate columns for each QICA administration in the table would work.

**Comment by kuoxes1** [comment]
FANCY!  Looks great :)  No bugs noted, I tried it in IE and Firefox and looks ok to me.... I think ready to push to production
