### ISSUE TITLE
Unassigned practices

### ISSUE THREAD

**Issue by squabwrangler** [seemack/healthy-hearts-northwest-dev#133]
This is a place holder for discussion on 10/19 (database meeting) for Nicole to weigh in on.

**Comment by squabwrangler** [comment]
Nicole will ask site managers to re-enter the coaches for these practices.

**Comment by squabwrangler** [comment]
From Clarissa 10/26/2016
"I read this this chain and there are several things going on here.  1) Attaching a coach to each encounter:  The qualitative data team would simply like to know if the coaches CHANGES (for example Todd left and other coaches have taken on this practices) to provide context for interpreting the notes, it has nothing to do with judging the coaches or assess who has dropped practices and everything to do with being able to understanding why PDSA might be phrased differently or other issues might be coming up but it isn’t the end the world if this is not technical possible, 2) Highlighting dropped practices on the landing page: this has nothing to do with the qualitative data teams needs.  3) What to do with practices that drop: I don’t think we have strong opinions about what happens with these practices as long as we have some qualitative data that clearly indicates that the practices has officially dropped and or has gone dark long enough that the coach is no longer contacting them and we know what type of coach category they get assigned to…like a coach named “DROPOUT”.   

None of what we are requesting needs to be on the landing page and we are not using it to provide any type of QA or formative evaluation. "

**Comment by kuoxes1** [comment]
not needed for qualitative analysis and we have coach changes tracked in DB and in trackers, so no reason to add this back into db
