### ISSUE TITLE
Mtn View Family Practice PAL issue

### ISSUE THREAD

**Issue by squabwrangler** [seemack/healthy-hearts-northwest-dev#135]
Email from Caitlin:
"Hi Erika,
Hmm. I am a bit confused about this. At one time, there were two entries for this practice. I worked with Elena and Kilian to delete one of the entries, but the second should be intact.  Emily has been recording her visits for this practice (see below), and they are definitely still part of H2N. What should I do to make sure we have all the information for this practice?"

Chris, please re-enter a check mark for PAL sent and returned for this practice (I am assuming you can do this without the system reassigning a practice ID?), per Caitlin:
The date on the PAL is 11/23/15

**Comment by seemack** [comment]
I'll add the PAL.

Visits are recorded separately from PAL-type "events" - those are saved with Practice-level information, not IVContact-level information.  If the wrong Practice record was deleted, we could definitely end up with incorrect PAL info.  But the fact that a Practice ID is assign suggests that either (1) a PAL was originally marked returned for this practice or (2) I moved the Study ID over but didn't move the PAL data over in deleting the duplicate.  I'm pretty good at making sure I square all the data before any such deletion, but it's still definitely possible.

**Comment by seemack** [comment]
I added the event with a note about how the data was entered.  Closing now since this is a data-only issue in production.
