### ISSUE TITLE
create a new staff contacts export (not replacing old one, adding a new one)

### ISSUE THREAD

**Issue by squabwrangler** [seemack/healthy-hearts-northwest-dev#137]
Please include practices with practice IDs, active and dropped, and the staff contact checkboxes with associated names and email addresses also add coach name.

**Comment by seemack** [comment]
Is this just practices with a practice ID (i.e., enrolled in some way?)  And is there any order that would be most helpful?

**Comment by kimbelk** [comment]
Yes, only practices with practice ID (i.e. enrolled or previously enrolled). Here's what I was thinking: practice name; practice ID; staff contacts; site; enrolled/ or not; & coach assigned. This is really all I need.

**Comment by kimbelk** [comment]
This export is AMAZING!!! THANKS!!!

**Comment by seemack** [comment]
Awesome! Let me know if there are any changes or improvements you have in
mind.  Otherwise I'll mark this issue as closed.
