### ISSUE TITLE
Create Full Table Exports

### ISSUE THREAD

**Issue by seemack** [seemack/healthy-hearts-northwest-dev#139]
For Kristin and anyone else who requires complete data exported directly from the database tables.  To emulate a SELECT * type of query, do something like this:
```
  def export
    ivcontact_csv = CSV.generate do |csv|
      csv << Ivcontact.attribute_names
      Ivcontact.order(:id).each do |iv|
        csv << iv.attributes.values
      end
    end
    respond_to do |format|
      format.csv { send_data ivcontact_csv }
    end
  end
```

**Comment by seemack** [comment]
Ivcontacts export is complete.

**Comment by seemack** [comment]
Used the ivcontacts framework to similarly export other tables in ApplicationHelper.rb.

**Comment by kuoxes1** [comment]
These all look correct to me.  the only thing i see is that IVcontacts etc export numbers not words for things like type and contact, you can either provide Kristin with a data dictionary or maybe just display words?
