### ISSUE TITLE
Coach Practices default to date of last contact

### ISSUE THREAD

**Issue by seemack** [seemack/healthy-hearts-northwest-dev#14]
Site contacts is in ascending order of date. Change this to descending order of date.

**Comment by seemack** [comment]
jQuery.dataTables was "helping" with this one. I overrode the default sort order by setting the data-order attribute in the table to 0 (first column) descending:

```html
<table class='typical enable-data-table' data-order='[[ 0, "desc" ]]'>
```

**Comment by rpardee** [comment]
Slick!  Looks good to me, FWIW.

But this has me noticing that the date format in the last QICA score header (mm/dd/yyyy) does not match the one in Site contacts (yyyy-mm-dd).  Do we want to make those match?

**Comment by seemack** [comment]
It would be nice to match.  Since this date is sortable, I want it to remain year-month-day.  That's less essential for Last QICA Date, but I agree, symmetry aids interpretation.
