### ISSUE TITLE
Data entry page for coaches - 

### ISSUE THREAD

**Issue by kuoxes1** [seemack/healthy-hearts-northwest-dev#141]
can be a separate page with a button to link to it that displays for all visits or a textbox within the visit
Here is the form they are filling out:  would be great for the data entry to match this for ease of entry

Please complete this information and enter it into the database practice page to the right of staff list button! "Survey Round 2"
1.	Practice Name:____________________________________________________

2.	To whom did you distribute the PS?  __________________________________

3.	How many staff did you distribute a SMS to?  ___ ___ people

4.	Any comments, questions, notes?_____________________________________________________________

**Comment by seemack** [comment]
I just noticed the official protocol has more fields than this.  Do we want to reflect the writeup in T2 PS Coach Protocol.doc?

![image](https://cloud.githubusercontent.com/assets/355833/21155486/34d5baba-c127-11e6-9f16-ef28b0692e02.png)

**Comment by kuoxes1** [comment]
So the data entry page should just have this - I think we beleived there would be more originally. 

The EXPORT will have more fields - this plus everything in the Survey EXCEL upload.

**Comment by seemack** [comment]
Quick update after talking to Elena:  build to the picture above, that's the new version.
