### ISSUE TITLE
Add fields to the qualitative export

### ISSUE THREAD

**Issue by squabwrangler** [seemack/healthy-hearts-northwest-dev#142]
1.  Please add the PDSA status at the time of saving the record to the qualitative data export.  We need to know this for coding these documents.

2.  Add coach name to the document (currently it's only in the title)

3. (revisit before you start on this step with Clarissa/Leah) 
potentially add current status (active/inactive) and date dropped to the qualitative export.   Leaning towards that it's not value added

**Comment by seemack** [comment]
Step 0:  Check for any text fields that have been added to the system since July.
Check db/migrate/ files since July for :string and :text types.

**Comment by squabwrangler** [comment]
Update: Let's discuss on Monday. #3 above is not necessary. We do need the Status of each PDSA: planning, continuing testing, abandoned, adopted, added to these records.

**Comment by seemack** [comment]
Added PDSA status, coach name and the "Other Topics Discussed" open text field for topics that aren't defined to be selected.
