### ISSUE TITLE
"Todd" issue adding current/prior coaches to qualitative export

### ISSUE THREAD

**Issue by kuoxes1** [seemack/healthy-hearts-northwest-dev#143]
Want to be able to query  by coach at the time of visit, or perhaps display all prior/current coaches... or.... 
Check with Clarissa when ready to work on this

**Comment by seemack** [comment]
This can't really be done without breaking current relationships - each practice has a single coach associated.  But every coaching change is logged in a table that's available for export.

**Comment by squabwrangler** [comment]
We will use the export to ascertain dates that a coach switched.
