### ISSUE TITLE
Weekly dropped info to add to "dashboard"

### ISSUE THREAD

**Issue by ltuz** [seemack/healthy-hearts-northwest-dev#144]
Michael requested information on a weekly basis for the H2N team huddle re: which practices have been dropped, re-entered, coach name and these variables:
drop_dt	drop_reentry_dt drop_notify_rsn_demanding	drop_notify_rsn_priority	drop_notify_rsn_barrier	drop_notify_rsn_relevant	drop_notify_rsn_other	drop_notify_rsn_specify drop_decide_why	drop_comments

How can we report this information easily on a weekly basis? MIchael wants to keep track of this so we're aware of how to deal with retention issues.

**Comment by seemack** [comment]
Elena took care of this.  Woo hoo!
