### ISSUE TITLE
Create a 15 month "graduation visit", 18 mo & 21 mo visits

### ISSUE THREAD

**Issue by kuoxes1** [seemack/healthy-hearts-northwest-dev#149]
We'd like the last required contact to be something you can pull down from the menu as "Graduation visit"
In addition to all the required monthly contact information, it would include a few other fields:
Practice plan for the next 6 months open text field
Any HLC they plan on working on
Etc.....

What do you think?  We'd need it live in production by first week of Febish....

**Comment by seemack** [comment]
How can we define this in database terms?  It'll either have to be tied to a specific in-person visit number, or be defined separately (maybe behind the scenes with a code like "99").

Anything else you have spec'd out would be helpful, too.  Is there a proposed layout or anything?  Let's especially flesh out the "etc." part of this.  :)

**Comment by seemack** [comment]
Per email:
They are asking that it be a separate visit, like we have in person visits, we have other required contacts, we have phone calls, they want it to have its own cool name 
“15th month graduation visit”  in the pull down menu….something like that!

**Comment by seemack** [comment]
I heard mention of 18mo & 21mo visits, too.  Do we want to build these out at the same time?

**Comment by seemack** [comment]
N.b., PDSAs should be forwarded to the 15mo visit, but that's the end.  18mo & 21mo visits should not have PDSAs forwarded to them.

**Comment by seemack** [comment]
15 month is ready for testing in a rather basic way.  18 & 21 to follow.

**Comment by seemack** [comment]
For those who are interested - 18 & 21 month visits are ready for testing, too.
The T3 Survey Tracking is not yet enabled.  Should this look identical(-ish) to the separate T2 page?

**Comment by kuoxes1** [comment]
this looks fine to me!
T3 survey tracking should look identical but will have variable names with a 3 to help me keep track :)
