### ISSUE TITLE
Coach Practice include all PDSAs

### ISSUE THREAD

**Issue by seemack** [seemack/healthy-hearts-northwest-dev#15]
Previously we've only displayed Abandoned & Adopted PDSAs.  Include continuing as well.

**Comment by squabwrangler** [comment]
one thing is weird, it is auto filling the dates in the table even if there is nothing in the PDSA cycle area of the IV contact.  See Green Acres FP.

**Comment by rpardee** [comment]
I'm not sure how to easily pull that up (can you include the URL?) but I wonder if [Acme Family Practice](https://healthy-hearts-northwest-dev.herokuapp.com/coach_practices/14) doesn't also demonstrate the issue?  To me the relevant bit looks like this:

![image](https://cloud.githubusercontent.com/assets/26327/12457257/6e48154e-bf58-11e5-917a-a2f5dd6be9c7.png)

?  Is that what you're talking about?

**Comment by seemack** [comment]
Some of the old records may have blank PDSA data in there.  I think Roy fixed that since.  Can we replicate this issue with a new practice, or with an existing practice where we're inputting in-person visit (therefore PDSA data) for the first time?

**Comment by rpardee** [comment]
Yep, that's what I was thinking too.  That said, the pull req I just sent you includes the one-line fix needed to screen these out.  So either way...

**Comment by squabwrangler** [comment]
Yep, you are correct.  This seems to be working just fine on a new practice.
