### ISSUE TITLE
Change name of Qual Export to date parameters

### ISSUE THREAD

**Issue by seemack** [seemack/healthy-hearts-northwest-dev#153]
Currently using the current date - change file name of zip file to date params.

**Comment by kuoxes1** [comment]
When I try this I get a zip file, but there is nothing inside when I try to open?  0 documents inside the zipped file?

**Comment by seemack** [comment]
What was your date selection?  Depending on what you choose, it's possible there are no documents.  The system defaults to today's dates; there will almost definitely not be any IVContacts from 2/10/2017 to 2/10/2017 in dev.

**Comment by kuoxes1** [comment]
yeah looks fine to me now, weird...  I think it's ready to go.
