### ISSUE TITLE
Build out Tiering for visits after 5th

### ISSUE THREAD

**Issue by seemack** [seemack/healthy-hearts-northwest-dev#159]
The current questionnaire was designed to specifically list all 5 possible visits where the Tiering Tool is asked.  We're thinking about adding (at least?) a 6th, for the 15 month visit.  Is it possible that more than 6 quarterly, required, in-person visits will be held, and that we'll need more than 6?

**Comment by seemack** [comment]
I'm guess this is not an issue because we're going to define the difference between the 5th required visit and the 15mo visit?

**Comment by kuoxes1** [comment]
I agree I think this can be closed?
