### ISSUE TITLE
Coach Practice view - Make "Add New Site Contact" more obvious

### ISSUE THREAD

**Issue by seemack** [seemack/healthy-hearts-northwest-dev#16]
First-time user issue:  when no contacts have yet been added, coaches didn't know where to go.

Ongoing issue:  the title "Intervention Contacts" is not especially good.

**Comment by seemack** [comment]
(1) Added explanatory text in red to explain what to do on first use.
(2) Changed title to "Site Contacts."

**Comment by seemack** [comment]
I'm reopening this so it can be reviewed by others.  I'll try to find a label that makes that clear.

**Comment by squabwrangler** [comment]
Let's see if the newly trained coaches will miss seeing that practice page at all initially. Seems REALLY OBVIOUS NOW.  Nice work!
