### ISSUE TITLE
Post-coaching visits flagged in red

### ISSUE THREAD

**Issue by seemack** [seemack/healthy-hearts-northwest-dev#161]
The Coach Landing page flags as overdue practices where it's been more than 45 days since the last required visit.  The 15 month visit is not currently counting toward this, and even if it does, eventually early practices will be legitimately finished and should not be marked in red.

When should the "overdue" flag be turned off, and what should the last visit be that shuts it off?

**Comment by seemack** [comment]
Notes for me:
app\views\coach_practices/list.html.erb
`<% if practice.last_required_iv_contact_date && practice.last_required_iv_contact_date <= Date.today - 45 %><span style="color: red;">`
app\models\practice.rb
`def last_required_iv_contact
    self.ivcontacts.where({ contact_type: [1, 2, 4] }).order(:contact_dt).last
  end`

**Comment by seemack** [comment]
Monthly visits still required until the 15 month visit (which counts as required).  After the 15 mo graduation visit, turn off the flag.

**Comment by kuoxes1** [comment]
this looks good to me!

**Comment by squabwrangler** [comment]
Currently on the coach landing page, this visit does not display the GYR rating, is that ok?  Also, on the practice page, if there is missing data, it does not mark the 15 mo visit with an exclamation mark. Ok?

**Comment by ltuz** [comment]
1) Original question: When should the "overdue" flag be turned off, and what should the last visit be that shuts it off?.....Answer: Do not add an "overdue" flag to the 15th month visit

2) Squabwrangler - doe the GYR not show up on the 15 months or where? I believe missing data even for the 15th month should include exclamation marks

**Comment by seemack** [comment]
Proposing we close this (if ready) and move status of missing data in 15mo survey to #165.

**Comment by squabwrangler** [comment]
tested. nice work!!!
