### ISSUE TITLE
Survey Status add more variables

### ISSUE THREAD

**Issue by seemack** [seemack/healthy-hearts-northwest-dev#163]
Add all “Other Information” lines (Personnel.site_contact_text) from Staff List in Recruitment side of database to Survey Status Export.

**Comment by seemack** [comment]
FWIW, since this is mostly blank anyway, I'm planning to cram all possible text into a single Excel column.

**Comment by squabwrangler** [comment]
I'll let Elena weigh in on this one.

**Comment by kuoxes1** [comment]
this is fine thanks!

**Comment by seemack** [comment]
Pushed to production. Closed.
