### ISSUE TITLE
Remove QICA from 21 month visit

### ISSUE THREAD

**Issue by seemack** [seemack/healthy-hearts-northwest-dev#166]
Now being asked at 15 months. Given that we don't know how 18 & 21 month visits are going to go, let's remove it.

**Comment by ltuz** [comment]
Can you clarify? Is this the 3rd QICA "now being asked at 15 months"? Or are you moving the second QICA (from Q4) to 15 months?

**Comment by seemack** [comment]
My mistake: the QICA isn't being asked at 15 months, it's simply being removed from the 21 month contact.
