### ISSUE TITLE
IVContact - Improve headers in Topics section

### ISSUE THREAD

**Issue by seemack** [seemack/healthy-hearts-northwest-dev#17]
Make clear which boxes include headers.
Potentially change table styling so aid in clarifying.

**Comment by seemack** [comment]
Reviewed by me - this looks much clearer.  I like.

**Comment by squabwrangler** [comment]
Nicole, will this work?

**Comment by seemack** [comment]
Reviewed at today's database meeting. Closing unless someone comes up with a better way of handling this.
