### ISSUE TITLE
add 15, 18, 21 visit dates to the coach landing page

### ISSUE THREAD

**Issue by squabwrangler** [seemack/healthy-hearts-northwest-dev#170]
From Rose Lauck: "Would it be possible to add 15, 18, and 21 month visit data into the “last required visits” column?  It would be lovely to see when the last significant contact is with my sites.  Currently, it looks like the last time I’ve connected with sites was in May and June."

**Comment by seemack** [comment]
Pushing this to dev.  Give it a spin & I'll push it to production when I'm back in town.

**Comment by squabwrangler** [comment]
when I try to log in to the dev site, I am getting this error message: "An unhandled lowlevel error occurred. The application logs may have details."

**Comment by squabwrangler** [comment]
This looks good!! Ready to push to production.
