### ISSUE TITLE
IVContact Staff Quick Add changes

### ISSUE THREAD

**Issue by seemack** [seemack/healthy-hearts-northwest-dev#19]
Generally, make this more like the Recruitment Staff Add.
(1) Include check boxes for subroles
(2) include optional email address
(3) Include "Other" and "Specify" for role (n.b., in Recruitment, too?)
(4) Mention that editing can be done in the Recruitment Area.

**Comment by seemack** [comment]
Added all specified fields. Now displaying email address on staff list for later use. We may want to remove this later if the Survey Contact is changed to a select box.

**Comment by squabwrangler** [comment]
Nicole or Elena, do we also want to see "Writes EHR reports" or "Helps with EHR reports" in this section as a checkbox? See the staff section of the recruitment practice page for reference.

**Comment by squabwrangler** [comment]
I just tested out the primary contact check box in the IV tracker, we need to highlight the importance of these checkboxes with coaches as there could be 2 people checked Primary site contact (one in the recruitment section and one here). It will not override a previous selection (in the recruitment section).

**Comment by seemack** [comment]
Leaving off EHR reports.  We'd included QI Champion because it was a requested role, but if that's the case, it should properly be entered as a role.  Dropping Primary Site Contact because (1) this isn't the place to ascertain who among the personnel is or isn't a primary contact, (2) there's no way to unmark another personnel as the primary contact and (3) the coach may or may not be assessing this anyway during the visit. Such work belongs in the Recruitment area Practice page.
