### ISSUE TITLE
IVContact - Contact for Staff Member Survey should be smarter

### ISSUE THREAD

**Issue by seemack** [seemack/healthy-hearts-northwest-dev#20]
We could either display the email address in the Staff List above (so folks can copy & paste from it), or better yet, this could be a select box that refreshes each time the Staff List adds a record.

**Comment by rpardee** [comment]
FWIW, I'd call it a win even if the drop-down didn't refresh, and we kept the existing boxes as a sort of "other--please specify".

**Comment by kuoxes1** [comment]
if they ask we'll reconsider, otherwise they can just copy and paste from staff section.  CLOSED!!!
