### ISSUE TITLE
Coach Practice - flag incomplete QICA

### ISSUE THREAD

**Issue by seemack** [seemack/healthy-hearts-northwest-dev#21]
Null values count as zeros for QICA calculations. Include a note/symbol/something so users can see on the Coach Practice overview that there are incomplete items in the QICA.

**Comment by rpardee** [comment]
How does per-HLC completeness grab you:

![image](https://cloud.githubusercontent.com/assets/26327/12434282/a118b01c-beba-11e5-8732-6e765ecbf66d.png)

?  Can that work?

**Comment by vanborkulo** [comment]
So I am clear, 'incomplete' means they didn't mark the answer to one of the questions. Correct?  I would view this as a rare occurrence, so think something less would be better. Maybe the column could be labeled 'missing data', and only an 'x' would show up if an answer is missing for that section.  (I don't want 'complete' vs 'incomplete' to be misconstrued as meaning something more than just missing answers.)

**Comment by kuoxes1** [comment]
I was just about to write in what Nicole said - I'm getting confused as to what complete means, but I like the icons!

**Comment by rpardee** [comment]
Yep, you guessed my intention accurately.  I will make the changes you mention.

**Comment by rpardee** [comment]
Here's the new:

![image](https://cloud.githubusercontent.com/assets/26327/12434828/1a804b60-bebe-11e5-972d-e8895f860f0e.png)

**Comment by seemack** [comment]
Maybe even leave off the Missing Data column entirely if there isn't any missing data??

**Comment by vanborkulo** [comment]
Yes. I think it there is no missing data - no column.  That is better, Roy!

**Comment by ltuz** [comment]
This looks good to me too, thanks Roy!

**Comment by rpardee** [comment]
Okay, it sounds like we don't need the column--I'll just do a general warning, as originally requested.  Like so:

![image](https://cloud.githubusercontent.com/assets/26327/12453322/8fd68f26-bf47-11e5-955b-4a7ba97eb267.png)

**Comment by squabwrangler** [comment]
looks good to me, Nicole?

**Comment by vanborkulo** [comment]
Yes

**Comment by rpardee** [comment]
Cool--thanks.
