### ISSUE TITLE
IVContact - Add "did not discuss" to HLCs

### ISSUE THREAD

**Issue by seemack** [seemack/healthy-hearts-northwest-dev#22]
HLCs will likely not be asked at the welcome visit.  In any case, offer an option of "did not discuss" that's visually separated from the other valid responses.

**Comment by seemack** [comment]
Manually added radio_button for each *milestone_[x]_progress* field with label "Did not discuss" and value 9.  I did not include this value in the ivcontact.rb model defintion because I wanted this value broken out and displayed separately from the other categories.

**Comment by rpardee** [comment]
So to figure out whether to show the HLC checbox for a given practice on http://localhost:3000/practice_contacts, I need to treat values of 9 as the same as nil, yes?

**Comment by vanborkulo** [comment]
Complete!
