### ISSUE TITLE
IVContact - New headers needed for Tiering Tool

### ISSUE THREAD

**Issue by seemack** [seemack/healthy-hearts-northwest-dev#23]
Per Nicole:

The new titles for the tiering categories are below.  These columns should be equal in size.

Limited Change Capacity
Basic Change Capacity
Moderate Change Capacity
Advanced Change Capacity

**Comment by seemack** [comment]
Because of the similar length titles, I'm letting the widths take care of themselves.

**Comment by vanborkulo** [comment]
Complete!

**Comment by rpardee** [comment]
Reopening at Erika's request.

**Comment by seemack** [comment]
Closing - issue #24 is the one that should be reopened.
