### ISSUE TITLE
IVContacts - Multiple descriptions too confusing

### ISSUE THREAD

**Issue by seemack** [seemack/healthy-hearts-northwest-dev#24]
Clicking on each header creates a pop-up box, but they quickly get confusing with too many. Preferably add a Title attribute to each.  If that isn't possible, have the boxes auto-close when the user clicks out of them.

**Comment by seemack** [comment]
Modified the js in ivcontacts.coffee. Add a Title attribute and add css to the close icon on initialization:
```javascript
	$('#ivcontact-tier3').on 'click', ->
		$('#tier3').dialog(
			closeText: "",
			width: 600,
			title: "Moderate Change Capacity",
			create: ->
				closeBtn = $('.ui-dialog-titlebar-close')
				closeBtn.css({ "position": "absolute", "right": "10px" })
		)
		$('#tier3').dialog('open')
```

**Comment by vanborkulo** [comment]
Assume this is for the tiering tool?  It is much better with the titles listed for each pop-up box. I'd say complete on this.

**Comment by seemack** [comment]
Thanks Nicole for the extra context - this is the tiering tool headers that display popup boxes via tooltips to provide additional explanation.

**Comment by squabwrangler** [comment]
Wait a minute...the descriptions of each are floating at the top of the IV contacts page (they disappear below, but are still present when you scroll up the page again).  Try it out.

**Comment by seemack** [comment]
Reopening per Erika's comment. Erika will help reproduce an error where clicking in the header makes the popup disappear from the screen and relocate to the top of the page.

**Comment by squabwrangler** [comment]
Emailing Chris a screenshot.
![image](https://cloud.githubusercontent.com/assets/16724444/12467429/254f6990-bf90-11e5-9467-d00842e307a2.png)

**Comment by squabwrangler** [comment]
Nicole had the same problem

**Comment by seemack** [comment]
Added css references to all jQuery UI components in application.css:
```javascript
 *= require jquery-ui/datepicker
 *= require jquery-ui/dialog
 *= require jquery-ui/draggable
 *= require jquery-ui/progressbar
 *= require jquery-ui/resizable
 *= require jquery-ui/tooltip
 *= require jquery-ui/tabs
```
