### ISSUE TITLE
IVContacts - Two comments boxes needed

### ISSUE THREAD

**Issue by seemack** [seemack/healthy-hearts-northwest-dev#26]
Replace the single comments box with two separate ones.  Per Nicole:

“Observations of environment and team dynamics” will be the title for the comment box at the top that should ONLY show up for the five in-person visits.

“Comments/Field Notes” will be the title for the comment box at the bottom that will show up for ALL visits including the newly designated HIT only visits.

**Comment by seemack** [comment]
Moved comments box to bottom of page.
Created new observations text_area displaying only for in-person visits.

**Comment by vanborkulo** [comment]
Looks good! I'd say complete.
