### ISSUE TITLE
LIveTables freaks out on browser back button

### ISSUE THREAD

**Issue by seemack** [seemack/healthy-hearts-northwest-dev#27]
No errors on the javascript back links, but the browser back button re-initializes tables and bombs.

See https://www.datatables.net/manual/tech-notes/3

**Comment by seemack** [comment]
Instead of checking for initialization, I can pass the option "retrieve: true" to tell the application I'm aware that the initialization options can't be changed after initialization, and should that occur, Ijust want the DataTable instance to be returned.

**Comment by squabwrangler** [comment]
This also seems to function just fine now (in dev) 1/15/2016  Nice work!
