### ISSUE TITLE
IVContact - Add "HIT Only" contact type

### ISSUE THREAD

**Issue by seemack** [seemack/healthy-hearts-northwest-dev#28]
Top of survey should be displayed (contact mode, dates, duration, field notes).

HIT Only will be its own Contact Type.

**Comment by vanborkulo** [comment]
Not seeing 'HIT Only' as an option.

**Comment by vanborkulo** [comment]
HIT only visits look good. One additional change if possible - can you remove the 'QI Processes' choices for these visits? Should only have the HIT and EHR vendor choices for topics

**Comment by seemack** [comment]
Wrapped QI Processes table in div#ivcontact-topic-qi-processes. Hide on HIT-only; show in all other instances in ivcontacts.coffee updateContactType().

**Comment by squabwrangler** [comment]
works well. Nicole, will we need to know who entered these notes? If not the coach?

**Comment by vanborkulo** [comment]
No. But, if it isn't a huge add, it would be great to have a box for the HIT coaches name. (Admin person will be filling out for all visits.)

Sent from my iPhone

On Jan 20, 2016, at 9:08 AM, squabwrangler <notifications@github.com<mailto:notifications@github.com>> wrote:


works well. Nicole, will we need to know who entered these notes? If not the coach?

�
Reply to this email directly or view it on GitHub<https://github.com/seemack/healthy-hearts-northwest-dev/issues/28#issuecomment-173276202>.

________________________________

GHC Confidentiality Statement

This message and any attached files might contain confidential information protected by federal and state law. The information is intended only for the use of the individual(s) or entities originally named as addressees. The improper disclosure of such information may be subject to civil or criminal penalties. If this message reached you in error, please contact the sender and destroy this message. Disclosing, copying, forwarding, or distributing the information by unauthorized individuals or entities is strictly prohibited by law.

**Comment by rpardee** [comment]
Chris will add drop-down to indicate which HIT coach made the contact. (Do this for all contacts/coaches?)

**Comment by vanborkulo** [comment]
No, should just be for the HIT coaches and these visits. All the rest of the visits will be done by the assigned coach anyway, so no need to identify. I will confirm the names for the drop down list.  (It will be two or three.)

**Comment by squabwrangler** [comment]
we decided that since any coach can enter a contact, we need a drop down to indicate which person entered the contact. Erika to set up meeting with Ross and Chris to discuss their work flow.

**Comment by squabwrangler** [comment]
This may relate again to the closed issue: IV tracker bombs when HIT coach is not defined"

**Comment by rpardee** [comment]
Just a nitpick here--the username of the person doing the data entry is automatically recorded.  I think what you want is a drop down to indicate which coach actually made the contact being documented.

(Or maybe I'm misunderstanding squabwrangler.)

**Comment by squabwrangler** [comment]
I think we will have to wait to understand this ask better from qualis/orprn to address this.

**Comment by rpardee** [comment]
Oooh--what I said about the username of the data enterer above is bullshit--the app does *not* currently record that.  Sorry for the misinformation.

**Comment by squabwrangler** [comment]
Erika will schedule a meeting with Caitlin and Chris next to discuss work flow.

Nicole and Elena, do you need to differentiate who collected the data, entered the data and who is responsible for the data (coach assigned to the clinic) for evaluation purposes?

**Comment by kuoxes1** [comment]
close this issue, its rolled into the multiple coaches for 1 practice
