### ISSUE TITLE
IVContact - HIT Tier should display every in-person visit

### ISSUE THREAD

**Issue by seemack** [seemack/healthy-hearts-northwest-dev#30]
Previously we've only included this in visits 1 & 5.  It should display for all in-person visits.

**Comment by seemack** [comment]
HIT Vendor only displays on first in-person visit.  HIT Tier and HIT Confidence display on all in-person visits.

**Comment by squabwrangler** [comment]
1/15/2016 I just tested this feature, looks/works great!  Nicely done!
