### ISSUE TITLE
Site User update requires password change

### ISSUE THREAD

**Issue by seemack** [seemack/healthy-hearts-northwest-dev#31]
By surfacing password on the Site User edit page, the form is passing along (blank) password changes when any other change is made, such as changing access level.  Non-password changes should not attempt to update passwords.

**Comment by seemack** [comment]
Modify partners_controller.rb to remove blank parameters from being passed on update. An attempt to blank out the user name or email would similarly fail to update those fields - but I can't imagine blanking out those fields (rather than changing them).

**Comment by squabwrangler** [comment]
This fix looks good in dev. 
I cannot figure out how to close this item. Perhaps you are the only person who can do this?
