### ISSUE TITLE
IVContact PDSA order is weird

### ISSUE THREAD

**Issue by seemack** [seemack/healthy-hearts-northwest-dev#34]
Previously entered PDSAs are listed at the bottom of the list rather than the top. Not sure if this is strictly an ordering issue or related to the pre-population of PDSAs for ease of data entry.
![image](https://cloud.githubusercontent.com/assets/355833/12428171/01c2517a-be98-11e5-8403-5ea01a9ddcaa.png)

**Comment by rpardee** [comment]
Aye, that's a fair cop.  I shall fix.

**Comment by rpardee** [comment]
Actually, playing with it, I'm not able to reproduce.  Is it possible that the blanks are earlier-added all-null records?  If you add some text to the description on say, that second item, then save & then go back into edit, does it come back in that second position?

If so, the best fix may be to delete all blank-description HLCTs.  There's right now a reject_if clause to the accepts_nested_attributes_for declaration in app/models/ivcontacts.rb:8 that keeps these things out, but before I did that, the app saved a bunch of empty HLCTs, which is what screwed up the (apparent) ordering.  IOW, I don't *think* we'd see this in the real app.

**Comment by seemack** [comment]
I'm similarly unable to reproduce - I think you're right, this is a problem with legacy data.  Shouldn't impact anything in the production site.  I'm happy closing it.

**Comment by kuoxes1** [comment]
Hi!  am I allowed to leave this comment?
