### ISSUE TITLE
HIT coach causes IVContacts to bomb when HIT coach is not defined

### ISSUE THREAD

**Issue by squabwrangler** [seemack/healthy-hearts-northwest-dev#38]
Just got an error message when I attempted to add an IV contact:

**Comment by rpardee** [comment]
Can you copy/paste the error message text into this issue?

On Wed, Jan 20, 2016 at 4:04 PM, squabwrangler <notifications@github.com>
wrote:

> Just got an error message when I attempted to add an IV contact:
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/seemack/healthy-hearts-northwest-dev/issues/38>.
>



-- 
Roy Pardee
http://datawranglr.com

**Comment by squabwrangler** [comment]
![image](https://cloud.githubusercontent.com/assets/16724444/12467485/9309fafe-bf90-11e5-806c-bd0a58c1d04b.png)

**Comment by seemack** [comment]
You must've hit that just as I was updating the database!  All should be
well now.

**Comment by squabwrangler** [comment]
not yet....

**Comment by seemack** [comment]
Ugh, this is happening on new IV Contacts, but not when an old IV Contact is edited.  Looking into it.

**Comment by squabwrangler** [comment]
ok, thanks!

**Comment by seemack** [comment]
HIT coach was not displaying on edit - probably related to the policy_scope on options_for_select for that field.  Added
```ruby
<%= f.select :hit_coach, options_for_select(policy_scope(Partner).order("name").collect { |p| [p.name, p.id] }, selected: @hit_coach_selected), include_blank: true %>
```
to view where @hit_coach_selected is defined in ivcontacts_controller.rb as
```ruby
@hit_coach_selected = @ivcontact.hit_coach
```

**Comment by squabwrangler** [comment]
HOLD until coach name drop down is added to the IV tracker for additional coach data entry.

**Comment by squabwrangler** [comment]
Leave a comment
