### ISSUE TITLE
Build dropout page

### ISSUE THREAD

**Issue by seemack** [seemack/healthy-hearts-northwest-dev#39]
Add some model fields relating to dropout.  Most likely tie this to Practices list in Manager area.

**Comment by ltuz** [comment]
The drop out looks good and works.  Maybe you guys chatted about this with Elena, but we need to know the reason for the drop out. It would help to add text to the open text box, something like, “Additional comments and reason for drop out or re-entry” or something to indicate we need the reason.

I was able to drop out a clinic and then re-enter them (woohoo!), but when I go to the re-enter screen, the question (“how was the dropout decision determined?”) that asks who determined drop out is still there. We would also want to know who determined the practice is re-entered so do we add to the pull down or does the question change when a practice is re-entered?

**Comment by kuoxes1** [comment]
change comments box wording to say:  “Additional comments and reasons for drop out or re-entry"

need to add a pull down that asks "who determined the reentry"

**Comment by squabwrangler** [comment]
It is confusing if a practice re-enters given that the language of the questions talks about dropping out only. Seems like this needs an additional pull down for when/if a practice re-enters.   Add 2 separate fields under General, one for entry date, one for a pull down that asks "who determined the reentry"

Comments should read: “Additional comments and reasons for drop out or re-entry"

**Comment by squabwrangler** [comment]
for the comments field:  

Additional comments and reasons for drop out or re-entry.  Please do not delete previous comments when updating.

**Comment by ltuz** [comment]
please remind me, what is the ETA for the dropout/re-enter to be tested and then pushed to production? unfortunately I'm hearing about more drop outs from Qualis and we need for them to begin entering this info.

**Comment by seemack** [comment]
This will be ready for testing this afternoon.  As soon as we get signoff, we can push it to production.

**Comment by ltuz** [comment]
Before you get it ready for testing just wanted to point out that per IRB rules, please remove the word "study" and "the" before Healthy Hearts Northwest. For example, the red font should read: Warning. You are about to drop Big Dumb Practice from Healthy Hearts Northwest

**Comment by seemack** [comment]
Wording changed. I've left the "How was the dropout decision determined?" question visible but disabled when a clinic re-entering the study. Marking this Ready for Testing.

**Comment by ltuz** [comment]
When I tested I noticed that if I intended to drop a clinic and hit "Drop", but I forgot to add something, whatever I entered was no longer available so all I could do was "reenter" which I didn't want to do so that I could "drop out" again and recreate   - is there any way just to make this simpler for the user?

**Comment by squabwrangler** [comment]
Is there a way to display both boxes (drop out and re-entry) so that we can edit or change information from a single page (titled "drop out/re-entry")?  An alternative (if easier) is to have an "edit" button so that if information needs to be added/changed, it can be done.

**Comment by ltuz** [comment]
Michael asked at today's 11:15 huddle that the Drop Out feature be ready as soon as possible, so please let us know when it's ready to be-retested. Thanks!

**Comment by seemack** [comment]
It's ready now - it depends on what we want to do with it.  It seems we're
still trying to figure that part out.  The programming is a small amount of
time by comparison.

**Comment by ltuz** [comment]
Let's talk about drop out on Thurs at our DB meeting. I believe you already pushed it out to production, right?

**Comment by kuoxes1** [comment]
We'd like to always show past information.  
Once someone drops out, the information about why they dropped out disappears if you go to look/edit/reenter.  We want all information to be seen and editable.

As long as we can reenter, then we can edit data, and then drop out....

**Comment by kuoxes1** [comment]
If this turns out to be a hassle - common thing that people drop out and then need editing, we will revisit this issue, but we're closing it for now.
