### ISSUE TITLE
Add dropout fields to data exports

### ISSUE THREAD

**Issue by seemack** [seemack/healthy-hearts-northwest-dev#40]
New practice dropout elements will soon be added.  Let's make sure those are in the data exports, too.

**Comment by rpardee** [comment]
Can do.

**Comment by seemack** [comment]
I've added a new Practice method called active.  It's set to 1 by default in the database.  Right now the only way to set it to 0 is to have the practice drop out, but I figured if we decided to hide rather than delete practices, we could use this field for that purpose, too.
