### ISSUE TITLE
Remove dropped-out practices from reports

### ISSUE THREAD

**Issue by seemack** [seemack/healthy-hearts-northwest-dev#41]
When this has been added - we'll want to filter the displays & reports to exclude practices that have dropped out.  Waiting on me.

**Comment by seemack** [comment]
Same comment as I made for issue #40 :  there's a new Practice method called active.  Filtering on active = 1 or true will get you only the active practices.  There's also a method called inactive_rsn that describes the reason the practice was made inactive.  Right now, the only possible value is 1 for dropout.

**Comment by rpardee** [comment]
I've removed these from the two dashboard things I did in my latest commit.  The other things that list practices that I can think of are:

1.  the recruiter area (partners/index): not done
2.  the manager area (coach_practices/:id/list): not done
3.  the practice list (practices/index): done

Are there others?

Shall I do those first two?

-Roy

**Comment by kuoxes1** [comment]
because this is intention to treat, they need to stay in recruiter and manager area because they will be randomized and might come back into the study.
