### ISSUE TITLE
Database export for surveys

### ISSUE THREAD

**Issue by kuoxes1** [seemack/healthy-hearts-northwest-dev#42]
It would be great if I could get a data dump that has the variables below.  I don’t mind if it has MORE than these columns, but it would be super helpful for me to track practice and staff member surveys and to do the weekly recruitment reports if I had all these variables in 1 spreadsheet.  I could either 
1.	get a data dump every Friday or
2.	click a button and generate one when I need it

5 digit Study ID
Practice Name
practice address
ORPRN/QUALIS
Pal Signed date
Primary Contact
Primary contact email
Staff member survey contact name (from First in person visit)
Staff member survey contact email (from First in person visit)
Welcome visit date
Dropped
Coach Name & e-mail.

Limit to practices w/signed PALs.

If it makes sense to roll up this data dump into something else, that’s fine, but it seems like what I need is partially in the recruitment data dump, and partially IV tracker stuff…. So it might be something separate….

**Comment by rpardee** [comment]
To me 'export' implies that you'll be doing your own filtering of practices that have already responded to a given survey. So there's no need for the app to e.g., record who has responded so it can do that filtering for you.  Is that right--this is one-way only?

**Comment by kuoxes1** [comment]
yes you do not need to add filters, I just need a data dump of all practices with these fields, and I will sort.

**Comment by rpardee** [comment]
note to self: coach id = partner.id.

**Comment by rpardee** [comment]
NO pal date--just pal status.

**Comment by rpardee** [comment]
I'm assuming "welcome visit" = "first in-person visit"--please let me know if that's not true.

**Comment by seemack** [comment]
Exactly right:  "welcome visit" = "first in-person visit"

**Comment by rpardee** [comment]
Cool--thanks.

Okay--I just pushed a first stab at the requested export.  Once that's merged & then deployed to dev, you'll find the link "Surveyable Practices Export" on the Manager View page.

**Comment by squabwrangler** [comment]
Elena and Erika say this looks good!  Nice work!
