### ISSUE TITLE
 IV contacts data export 

### ISSUE THREAD

**Issue by kuoxes1** [seemack/healthy-hearts-northwest-dev#43]
Need a ginormous data dump for Allen/Clarissa/Elena to use for QC

5 digit study ID
all the site visit data
All contacts (emails, phone etc

**Comment by rpardee** [comment]
Starting on this.

**Comment by rpardee** [comment]
Where should the link to this go?  It's GHC admin staff only using this, right?  I'm thinking admin area is probably best.  Do we care?

**Comment by kuoxes1** [comment]
Yes I agree admin only!
________________________________

**Comment by rpardee** [comment]
Okay--preliminary stab at this is done--look for the 'export intervention contacts data' link on admin page.  Chris will let us know when he's pushed this out to dev.

**Comment by kuoxes1** [comment]
This looks great!  Two minor tweaks:

Can you please add a column for dropped out (don't need everything, just date or something so we can filter these out if need be)

Also please add in coach name.

Thanks!

**Comment by rpardee** [comment]
Done. (In code--not yet pushed to dev.)

**Comment by squabwrangler** [comment]
Heads up, I have a meeting that will need this in the prod site by 2/18/16. Is this do-able?

**Comment by squabwrangler** [comment]
just received an error message when I tried to open this. "we are sorry but something went wrong"

**Comment by rpardee** [comment]
Yep--reproduced.  Sorry for the trouble.  I believe I see the problem--it's
an easy fix.

On Mon, Feb 8, 2016 at 12:01 PM, squabwrangler <notifications@github.com>
wrote:

> just received an error message when I tried to open this. "we are sorry
> but something went wrong"
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/seemack/healthy-hearts-northwest-dev/issues/43#issuecomment-181505131>
> .
>



-- 
Roy Pardee
http://datawranglr.com

**Comment by rpardee** [comment]
Okay, fix pushed to my repo & generated a pull request for Chris.  I'll ping Chris about merging & pushing it out to dev post-haste.

**Comment by rpardee** [comment]
Chris is done--please try again.

**Comment by squabwrangler** [comment]
No bug anymore!  Yeay! 
Are the comments from "observations" and "field notes" (and any other areas with text boxes) included in this report?

**Comment by rpardee** [comment]
"Comments and field notes" yes, "Observations of Environment and Team Dynamics" no.

Also no:

- "Please explain why your are not confident about this practice's ability to produce quality ABCS data."
- GYR Activities or Situations for Rating

Do you want all of those in this export?

**Comment by squabwrangler** [comment]
Roy is optimistic that one of the efforts they are working on will work to produce this output for us so that we can click on the export and get what we want... The stop gap measure is that Roy/Chris will do a local excel generation so we have data for next Thursday.

**Comment by squabwrangler** [comment]
Yes we want:
"Comments and field notes" 
 "Observations of Environment and Team Dynamics" 
•"Please explain why your are not confident about this practice's ability to produce quality ABCS data."
•GYR Activities or Situations for Rating

PDSA is a can of worms.... let's NOT  include that in this export for now.

**Comment by squabwrangler** [comment]
Has this been pushed to production?

**Comment by rpardee** [comment]
I don't think so.
