### ISSUE TITLE
Highlight missing data that is required for randomization

### ISSUE THREAD

**Issue by kuoxes1** [seemack/healthy-hearts-northwest-dev#44]
We need a display or a flag or SOMETHING of the 10-15 items from the recruitment database that are missing and are critical information for us to have at baseline or to do randomization etc. 

This list will be generated by Allen/Rob/Fey/Elena/Michael by mid Feb....

**Comment by kuoxes1** [comment]
on the coach practice display, and the landing page 

we'll add a column for a flag if the critical recruitment questions have any blanks.  There will be a  link to take them to the recruitment view

In the recruitment patient characteristics section, we highlight or bold or somehow else flag these questions so they are easy to find with a scroll through

STIll waiting for the final critical question list

**Comment by vanborkulo** [comment]
Love the flag for missing recruitment info!

**Comment by rpardee** [comment]
Dummied this up w/a list of required fields pulled out of my butt:

![image](https://cloud.githubusercontent.com/assets/26327/13261322/6b5b7822-da14-11e5-9a1d-69b57b790d7d.png)

and

![image](https://cloud.githubusercontent.com/assets/26327/13261333/7ca91e0e-da14-11e5-83f7-057e0b5802e3.png)

Once the actual list of required fields is determined it should be easy to switch those around.

If/when we figure out where we want to flag practices w/this incomplete info (on the default manager view maybe?) it should be easy to add this.

**Comment by squabwrangler** [comment]
Randomization will now be based on the practice survey being completed so now we just need a flag for when the practice survey is completed (currently issue #57 )

**Comment by squabwrangler** [comment]
no longer relevant - now its turned into practice survey nag which is a different issue
