### ISSUE TITLE
 Design & test sections to document intervention arms

### ISSUE THREAD

**Issue by kuoxes1** [seemack/healthy-hearts-northwest-dev#45]
place holder... They are still trying to figure this out.....
4/1/2016

**Comment by seemack** [comment]
We'll need to know if this information is being communicated to the coaches.  If not, there's no reason to track it in the database.  If so, we'll need to talk about what are the coaches going to do with the information to assess the best place to put it.

**Comment by kuoxes1** [comment]
Form today sounds like we are going to let  coaches know about which arm they are in BUT There will be no surveys, questions, other kind of documentation needed, let's keep this tabled for now until we know more!

**Comment by kuoxes1** [comment]
By april 15ish we need fake data to Chris.
By april 30 we need to have a mechanism to upload the randomization - there are 4 arms, and we need a back end upload
Need to have it display somewhere prominently for coaches - a logo?  initials?  Something

**Comment by seemack** [comment]
Consider the best way to note "enhanced intervention arms."  Maybe a pictogram with a tool tip describing the intervention?  A heart for Cardiovascular Risk?  A car for Site Visit?  A red apple for Learning?

**Comment by squabwrangler** [comment]
June 15th randomization group assignments will be available. Practice ID's with #1-4 for the 4 group assignments.  Elena to send a template with explanations of each arm to Chris.

**Comment by kuoxes1** [comment]
Arm	Abbreviation	Icon
1	usual care	TBD
2	site visit	TBD
3	Affinity group	TBD
4	both interventions	TBD
**Display** 		
On coach landing page		
	replaces spot that says "ready for randomization?"	
	displays an icon or an abbreviated version if we don't come up with an icon!	
**Upload**		
csv file named randomization.csv		
variables:		
	practiceID	
	Arm

**Comment by kuoxes1** [comment]
**Upload specs**		
csv file named randomization.csv		

**Variables:**	PracticeID, Arm	

Arm	Abbreviation	Icon
1	usual care	TBD
2	site visit	        TBD
3	Affinity group	TBD
4	both        	        TBD

**Display** on coach landing page		
	replaces spot that says "ready for randomization?"	
	displays an icon or an abbreviation of arm  if we don't come up with an icon!	

**Export** into Practives.csv and IV contacts Export

**Comment by squabwrangler** [comment]
Elena sent templates to Chris and Fei, Chris is on it!! Chris on vacation June 25-July 7th.

**Comment by seemack** [comment]
Here's the basics for connection:

1. Run migration that creates Practice.group_assignment (if not yet done).

2. Get credentials from Heroku:
heroku pg:credentials DATABASE_URL --app healthy-hearts-northwest-dev
You'll need the location at AWS, user name, database name & password.
These are also available from Heroku Dashboard/PostgreSQL

3. Connect to Heroku:
psql -h [AWS location above] -p 5432 -U [user above] -W -d [database above]
password: [password above]

4. Create new table
create table random_upload
(study_id char(5) PRIMARY KEY,
 group_assignment integer NOT NULL
);

5. Upload data
\copy random_upload from 'E:\Dropbox\GHRI\H2N-random.csv' (HEADER, FORMAT csv);

6. Update data
update practices
set group_assignment = random_upload.group_assignment
from random_upload
where practices.study_id = random_upload.study_id;

7. Drop temporary table
drop table random_upload;

**Comment by seemack** [comment]
Works in dev.  Should work fine in prod.  I'll go over this with Roy to see if it's fairly simple for him to do this, or if he requires new/different credentials to have access.

**Comment by kuoxes1** [comment]
Just need to make sure that it's part of the practices export and the IV trackers export.  The display looks fine!

**Comment by ltuz** [comment]
Here's some clarity and changes on how the intervention arms are displayed (changes have an asterisk)

Arm Abbreviation

 *1 Coaching Only
 2 Site Visit

 *3 CV Education

 *4 Site Visit/CV Education

Display

 On coach landing page

 replaces spot that says "ready for randomization?"

 *displays_ Abbreviation "Intervention arm"

 On coach practice landing page

**Comment by kuoxes1** [comment]
on coach landing page, should say "arm" not "usual care arm" as the header
usual care, site visits, CV Ed, site visits/CV Ed are the labels instead of the numbers that display.

within the practice landing page
group assignment should say  "Arm Assignment"

in practice export and ivcontacts export we need it to have 1,2,3,4 (no label)

**Comment by kuoxes1** [comment]
Consuelo will tell Chris when ready to send:

data - randomization - randomization documentation and protocol  
G:\CTRHS\Inst\AHRQ Healthy Hearts Northwest\DATA\Randomization\H2N randomization protocol and dataset.xlsx

**Comment by seemack** [comment]
Okay, actually complete, but I want everyone to be happy with the export, too, before closing this entirely.
