### ISSUE TITLE
General monthly program management updates

### ISSUE THREAD

**Issue by seemack** [seemack/healthy-hearts-northwest-dev#46]
Create a section in the Manager area to track barriers/challenges/successes/needs of their coaches on a monthly basis.

View a display of these topics in the Manager area sorted by type of topic and date descending.

Original document in
G:\CTRHS\Inst\AHRQ Healthy Hearts Northwest\DATA\Database\Programming Tasklists\Program Management
[Program Management sections nvb edits.docx](https://github.com/seemack/healthy-hearts-northwest-dev/files/108645/Program.Management.sections.nvb.edits.docx)

**Comment by seemack** [comment]
Each ORPRN and Qualis can only see their own Management Notes.  GHRI staff can see all such notes.

Navigate there via Manager Area ... General Tasks ... Program Management Notes.

**Comment by kuoxes1** [comment]
Nicole's comments:
Add "in the last month"  in the three topic areas at the beginning.
Want all the barriers/answers listed in the same place with name indicated.
We will test logged in as different people to make sure it works

**Comment by squabwrangler** [comment]
Per Nicole:  "I just looked at the section on the dev site.  Looks fine to me."
