### ISSUE TITLE
Assigning multiple coaches to one practice

### ISSUE THREAD

**Issue by squabwrangler** [seemack/healthy-hearts-northwest-dev#48]
We need a way for multiple coaches to be assigned to a practice (for HIT coaches and regular coaches to view the same practice).  Ross also asked for this functionality (2.1.16): "Would it be possible to add two coaches to one clinic in the coaching database? For some of our clinics, we will have a secondary coach participating in clinic visits and coaching. Both coaches may need to access the clinic’s coaching database section from time to time. Right now, we are sharing passwords and reassigning clinics back and forth as needed but it would help if we could assign the secondary access to their secondary clinic without using those work-arounds."

**Comment by seemack** [comment]
This would have been easy to if we'd talked about this during initial planning. It's very difficult now that we've associated practices with a single coach. To try to change that relationship everywhere in the database would likely cause catastrophic errors. Maybe there's some sort of "second best" solution that will be helpful enough?

**Comment by ltuz** [comment]
With ORPRN/OHSU, they have two coaches working with one practices (they have 1 PERC and 1 HIT PERC) but maybe it's not set up as Qualis is asking about. What potential solutions are there?

**Comment by kuoxes1** [comment]
Elena will Email Caitlin/Carolyn/Ross to ask if we can have a database call with them
1.  What exactly an extra coach needs to see.
2.  Can we just make the a manager so they can go into manager view and see other practices not assigned to them if needed?

**Comment by squabwrangler** [comment]
option #3 is to be able to navigate to other coaches clinics from in their own view similar to the recruitment section.

**Comment by squabwrangler** [comment]
~I just spoke with Caitlin, ORPRN will only need the HIT coaches to be able to enter data for specific practices (she can provide us with a list of which HIT coach enters data for which practice so we can identify them in analysis) so for them, making coaches managers would work IF we hide the data export dashboards from them. Chris, if you want to talk to Caitlin, we can set up a time for this.
~Qualis- coaches will need to cover for other coaches periodically. I think we could make all of them managers if we hide the data export dashboards as well although the question remains: do we need to know who entered data for each practice (IV) contact? If so, we would need a drop down or some way of capturing this per IV contact.

**Comment by rpardee** [comment]
By "data export dashboards" do you mean the entire [Manager Area](http://healthy-hearts-northwest-dev.herokuapp.com/supervisor_area), or some portion of it?  If only a portion, can you say specifically which links you mean?

Does your motivation to hide these things come from a "it would be harmful if they were able to see this information" kind of place, or is it more "they won't need this info so let's not burden them with it"?

![image](https://cloud.githubusercontent.com/assets/26327/13236801/a96e03e4-d97b-11e5-8d43-c9007395fa75.png)

**Comment by squabwrangler** [comment]
The only area that coaches would need to see in order to enter data for each other is the coach list. Am I thinking about this correctly?

**Comment by seemack** [comment]
Standard access coaches get a link to the Coach List in the place where Manager Area is displayed in the header.  Managers can still get there, of course, by first selecting Manager Area ... Coach List.

**Comment by seemack** [comment]
N.b., right now I'm not tracking which user added data to a particular practices.  We know who the coach is for each practice, but not necessarily the data entry person.  Do we want this?  Are there other areas (e.g., the Recruitment section) where we want the data entry person noted?

**Comment by kuoxes1** [comment]
Erika made all QUALIS coaches into supervisors.
Erika still needs to make some of the ORPRN folks into the enhanced coach status

Chris made all ORPRN folks with enhanced coach access able to see the display.

**Comment by squabwrangler** [comment]
This looks good to me as long as we do not want to capture the HIT coach whom is entering the data for any given Practice.  If we need that from an evaluation POV, we need a process in place.

**Comment by squabwrangler** [comment]
Caitlin gives this the thumbs up to go out!  Thanks!
