### ISSUE TITLE
PDSA data export

### ISSUE THREAD

**Issue by squabwrangler** [seemack/healthy-hearts-northwest-dev#52]
We want this but it's low priority for now.  When we start developing, it will be complicated - do we want to jsutpull the most recent?  First 6?  Need to consider frequency of pull and now "fresh" the data need to be.

**Comment by vanborkulo** [comment]
How about just the ones from the previous month presuming Clarissa (and I) want data exported at least monthly?

**Comment by kuoxes1** [comment]
this is rolled into` Clarissa's request so we are closing it
