### ISSUE TITLE
Practice list export

### ISSUE THREAD

**Issue by squabwrangler** [seemack/healthy-hearts-northwest-dev#53]
timing out:

Roy is optimistic that one of the efforts they are working on will work to produce this output for us so that we can click on the export and get what we want... The stop gap measure is that Roy/Chris will do a local excel generation so we have data for next Thursday.

**Comment by seemack** [comment]
I'll push it to prod early tomorrow morning. This will have my event streaming code, too.  I've encapsulated it in a separate method in case we decide to point it back to index.csv.erb.

```ruby
  def export
    export_name = 'practices.csv'
    @practices = policy_scope(Practice).all
    response.headers['Content-Type'] = 'text/event-stream'
    response.headers['Content-Disposition'] = "attachment; filename=#{export_name}"
    render :template => 'practices/export.csv.erb'
  ensure
    response.stream.close
  end
```

**Comment by seemack** [comment]
So so so much faster in production now. Roy & I can argue about who gets the credit.

**Comment by rpardee** [comment]
Me!  It was Me!

But also Chris.  Probably mostly Chris...

On Thu, Feb 11, 2016 at 6:53 AM, Christopher Mack <notifications@github.com>
wrote:

> So so so much faster in production now. Roy & I can argue about who gets
> the credit.
>
> —
> Reply to this email directly or view it on GitHub
> <https://github.com/seemack/healthy-hearts-northwest-dev/issues/53#issuecomment-182896124>
> .
>



-- 
Roy Pardee
http://datawranglr.com

**Comment by squabwrangler** [comment]
github is making this so much more fun.....I'll test this tomorrow.

**Comment by squabwrangler** [comment]
Elena, please test. looks good to me.

**Comment by kuoxes1** [comment]
runs up to speed good to go!
