### ISSUE TITLE
Add comments fields that may impact eligibility

### ISSUE THREAD

**Issue by squabwrangler** [seemack/healthy-hearts-northwest-dev#54]
add comments to Eligibility #7 and Practice Characteristics #10 

open ended comment box? "please document any anomalies/concerns"

**Comment by seemack** [comment]
There may be some wiggle room in assessing eligibility. Adding these two fields would allow recruiters to mark practices as eligible, but note any questionable circumstances.

**Comment by kuoxes1** [comment]
let's just put this as #7 under eligibility.... forget having it under practice characteristics as well.

title "Please list anomalies/exceptions that make this practice eligible despite not meeting all criteria ( EHR not yet certified, >10 clinician FTE, etc)"

**Comment by squabwrangler** [comment]
Looks good to me.

**Comment by kuoxes1** [comment]
Me too!
