### ISSUE TITLE
duplicates aaahhhhhhh

### ISSUE THREAD

**Issue by squabwrangler** [seemack/healthy-hearts-northwest-dev#55]
Where are we with this??

**Comment by seemack** [comment]
Duplicates that have been identified are gone.  There are still 2 special cases I haven't handled, where the same staff works in two different clinics.  It's suggested we delete the two clinics below - I just want to make sure we're agreed first.

Washtucna Medical Clinic- Clinic in separate location but same staff as EARH Ritzville  (different town, patients; same staff)
Coulee City Family Medical - Staff from Coulee family work in this clinic (different town, patients; same staff)

After that, we can either keep this issue semi-permanently open as a reminder, or close this and handle new duplicates as they arise.

**Comment by kuoxes1** [comment]
Elena will contact QUALIS to confirm what we are doing with these practices....  these are the husband wife team issues??  Or.....

**Comment by seemack** [comment]
All deleted and up-to-date as of 5/20. Let's talk about whether this should stay open as an ongoing issue, or if it should be closed and duplicates can be handled as needed.

**Comment by kuoxes1** [comment]
Nicole send email to coaches to say if you see any further duplicates, please let us know, otherwise we t think we found them all...
