### ISSUE TITLE
Survey status display in database

### ISSUE THREAD

**Issue by kuoxes1** [seemack/healthy-hearts-northwest-dev#61]
Practice, Staff Member need a display for sent/complete (practice survey) and sent/%complete(staff member survey) once we have it imported.

**Comment by rpardee** [comment]
Below is a screenshot of Ross' current spreadsheet.  I think we cleared up with him in e-mail that the db does not currently track welcome letter sent dates or welcome visit scheduling, so those columns are no-go's I think.  But the Practice & Staff survey bits should be doable I think.

My inclination is to make this another sort of 'dashboard', to be accessed off the 'Manager Area'.  Can that work?

![image](https://cloud.githubusercontent.com/assets/26327/13895034/d78770bc-ed2b-11e5-9d88-4abcad8260af.png)

**Comment by squabwrangler** [comment]
The coach view looks awesome!!!!   No changes needed to practice survey "randomizable?" 
Can we add Q20154 complete =1 from excel spreadsheet (don't need to add other quarters)

**Comment by rpardee** [comment]
So, trade-off time.  I've right now got this working:

![image](https://cloud.githubusercontent.com/assets/26327/14262428/55d91754-fa6a-11e5-9973-dfc9e25b1ad6.png)

Up-side is--nice & colorful.  The down-side is: no sorting or filtering.  if I enable the sorting/filtering, the page turns to this:

![image](https://cloud.githubusercontent.com/assets/26327/14262529/e60cc32a-fa6a-11e5-9b81-fd6c16ad75ff.png)

It may be possible, in the fullness of time, to get both, but not in the short term (and note I go on PTO starting Wednesday & am gone basically until the end of the HCSRN conference).

Which would you like implemented short-term?

**Comment by vanborkulo** [comment]
I think sortable is more important than color at this point.  If they want to look at one coaches teams, it would be very frustrating to have to look through and find info.

I LIKE the color one better, however. :-) Maybe down the road?

**Comment by rpardee** [comment]
Sounds good--I shall send Chris a pull request.

**Comment by kuoxes1** [comment]
ABCS survey still isn't appearing, everything else looks good

**Comment by kuoxes1** [comment]
chris will clean out the practice and staff data and elena will reupload 
Elena will let them know we are updating that

**Comment by seemack** [comment]
All data was cleaned out Friday a.m.  We've integrated Roy's changes - we'll know if all looks well after the re-upload.

**Comment by squabwrangler** [comment]
Elena uploaded these. Chris needs to reevaluate the enable/disable properties of the upload function.
