### ISSUE TITLE
IV tracker data export link for managers

### ISSUE THREAD

**Issue by squabwrangler** [seemack/healthy-hearts-northwest-dev#62]
Ross is asking for access to the IV tracker data export. Can we move this to the manager's area?  Is there any reason NOT to do this?

**Comment by kuoxes1** [comment]
Nicole, can Ross just ask you if/when he needs it?
Nicole, is there any reason all managers (Ross Caitlin, CArolyn) should not have it?
We dont' want real time data out there for paper writing etc.

We'd want to make sure that all coaches (Who are all supervisors) wouldn't get access
WE'd want to make sure that they only have their site (ORPRN/QUALIS)

**Comment by squabwrangler** [comment]
Nicole confirms that she will email Ross/CAitlin periodically, no one besides ghri staff will have access
