### ISSUE TITLE
missing IV contact data flag

### ISSUE THREAD

**Issue by squabwrangler** [seemack/healthy-hearts-northwest-dev#64]
Build a feature that flags contacts on the coach practice view when any data for the required visits (in person or other) in the IV tracker is missing (Observations comments, at least one "topic" should be checked, there should be at least one PDSA cycle beyond the Welcome visit, HLC should be complete at each visit, Green yellow red should include activities and the rating, HIT confidence level, Tiering tool for capacity, QICA, Field Notes and Comments.

**Comment by squabwrangler** [comment]
Elena to email Clarissa and NVB for importance of this issue.

**Comment by kuoxes1** [comment]
They confirmed importance of this, as they are missing a lot of critical data.

**Comment by seemack** [comment]
I'd like to talk about where to integrate these and how to display.  Probably an icon (red exclamation mark?) in the Site Contacts list on the Coach Practice page?

**Comment by kuoxes1** [comment]
Add red exclamation point also to the coach landing page. with a mouse over to say "yuou are missing data"

**Comment by seemack** [comment]
Incomplete data notices show up at both the Practice level & Coach Practice page.  I've tested this pretty fully, but it's a terribly complicated algorithm, so I'd be happy to have some testing help.

**Comment by seemack** [comment]
Tested!  Thanks, Erika!
