### ISSUE TITLE
“Type of Contact” -> 15 required monthly contacts ADD a third option.

### ISSUE THREAD

**Issue by squabwrangler** [seemack/healthy-hearts-northwest-dev#65]
ORPRN now has more than 5 in person visits so we need a new category.  Under “Type of Contact” -> 15 required monthly contacts ADD a third option.  So the three choices for this category should read:

Quarterly in-person visit
Other required monthly contact (phone)
Other required monthly contact (in-person)

**Comment by kuoxes1** [comment]
Dump all the current ones into " other required monthly contact (phone) and we will update if any are "in person"

**Comment by seemack** [comment]
The current setup has "Other Required Contact," then offers a select box to choose among contact modes: Phone, In-Person, Email & Online.  In theory, we should be capturing everything already.

Sorry for being dense, but what exactly is the problem that this issue solves?  Would renaming "Other Required Contact" to "Other Required Monthly Contact" be sufficient?  If we do add the phone/in-person as a top-level option, do we want to eliminate the select box with the 4 "mode" options?  Is there a concern about missing email or online contacts, or should those reasonably be deleted anyway?

**Comment by squabwrangler** [comment]
1. Remove email from the mode drop down for any type of visit other than ad-hoc or HIT
2. Add to Type of contact:   
Other required Monthly contact (in-person)
Other Required Monthly Contact (phone/web)
3. Add "5" after  Quarterly in person visit

**Comment by seemack** [comment]
Please check that the fields that appear for particular types of visits (including mode) respond as expected.  HIT-only visits hadn't had a mode before - they do now.  I'll mark this as ready to test once I've pushed it to dev.
