### ISSUE TITLE
iv tracker - add if a practice spread H2N to entire clinic vs pod/team within clinic

### ISSUE THREAD

**Issue by ltuz** [seemack/healthy-hearts-northwest-dev#67]
Need to add field(s) to last in-person visit section of IV tracker/DB for coaches to document if a clinic worked on/spread H2N throughout the entire clinic or just with a pod/team within the clinic. This came from a Monday huddle discussion and we might need to bring Nicole into the discussion to make sure she agrees with whatever new fields are added.

**Comment by kuoxes1** [comment]
Is this meant to be for the last time they visit?  
What fields are needed:
how far were you able to spread H2N?  drop down:  full clinic, one pod/team, other
Text box to add comments
Any plans to spread further? 

Please add to this list as we generate more ideas

**Comment by ltuz** [comment]
Nicole suggested this could be observed and documented by coach at last in person visit. Please ask Nicole for what info coaches can collect.

**Comment by squabwrangler** [comment]
Nicole, this is the issue that we wanted your input on.  Leah should be included on this discussion.

**Comment by vanborkulo** [comment]
I actually think it might be best to just have a comment box and a prompt such as, "Consider the team you initially worked with at this site as part of H2N. Did this practice spread their work beyond that original team - internally or to another clinic in their system?  How did this happen?  Please describe any spread activities."

I think we need to confirm with Clarissa, however.

**Comment by kuoxes1** [comment]
Add to V5 in person visit:
1. Who have you worked with at the clinic? (a team, a pod, whole clinic)

2. Did you see spread of this work from your initial team over the course of H2N participation?

3. Any plans to spread further?  (text box)

4.  Sustainability of this work?

**NICOLE**: work with  Katie Leah and others to figure this out 
get Chris specs by end of Sept for troubleshooting
Fielded by end of October

**Comment by kuoxes1** [comment]
Leah and Katie discussing adding to Staff survey 2 perhaps?  Do we also want coach perspective?

**Comment by kuoxes1** [comment]
Questions include:
On a  scale of 1-10, by role in clinic, who was involved in PDSA testing, something like that?

**Comment by seemack** [comment]
Can we close this out and fold it into #149 ?
