### ISSUE TITLE
IV contacts export issue

### ISSUE THREAD

**Issue by kuoxes1** [seemack/healthy-hearts-northwest-dev#69]
See this one fro an example:
Springfield Family Phys		Todd Noletto	Quarterly in-person visit	11/18/2015	Baseline	
Springfield Family Phys		Todd Noletto	Other required contact	12/22/2015	Baseline	In-person
Springfield Family Phys		Todd Noletto	Other required contact	2/18/2016	Quarter 2	In-person

The second row should not be showing up as a baseline in person should be blank
The third row should now show as a Q2 visit.

**Comment by seemack** [comment]
Closing this issue - it's an issue with underlying data (see Issue #72 ) rather than the data export.
