### ISSUE TITLE
Dropped practice info differs in data exports

### ISSUE THREAD

**Issue by squabwrangler** [seemack/healthy-hearts-northwest-dev#70]
From Leah, 3/16/2016:  I was looking at the Manager export tables and noticed there’s different info about “Dropped” clinics in the Practice Export table (the one with some missing info) and the “surveyable practice export” (this seems to have correct info per Ross).

**Comment by rpardee** [comment]
Can you say specifically what's different (e.g., "for practice X, field such-and-such has value A in the PE, and B in SPE.  B is correct.")?

Thanks!

**Comment by squabwrangler** [comment]
Leah made a mistake, not an issue.
