### ISSUE TITLE
give visual cue that a practice has dropped out on the coach view 

### ISSUE THREAD

**Issue by squabwrangler** [seemack/healthy-hearts-northwest-dev#75]

**Comment by rpardee** [comment]
Once this code is pushed, dropped-out practices should show up w/a dark gray background & a mouse-over tooltip explaining that the practice has dropped out:

![image](https://cloud.githubusercontent.com/assets/26327/14259708/feea96e6-fa5c-11e5-9529-d59673f50c13.png)

**Comment by rpardee** [comment]
Ack, sorry Chris--I neglected to include the changes I made to the Practice model.  I'm attempting to remedy this & am getting thwarted by our firewall:

```
[md]\healthy-hearts-northwest-dev> git push origin master
ssh: connect to host github.com port 22: Connection refused
fatal: Could not read from remote repository.
```

I shall keep trying...

**Comment by seemack** [comment]
I've pushed this to dev but don't see the gray background - either on dev or my local instance.

**Comment by rpardee** [comment]
I'm _guessing_ this is b/c of #77.  On my local I had to pull up the dropped-out practice on my local and null out the dropout_reentry_dt field.

**Comment by seemack** [comment]
Got it.  I'll try again after I've fixed that bug.

**Comment by seemack** [comment]
Hmm, I've been saving both the drop_dt and drop_reentry_dt at all times - if someone reenters, it keeps their drop_dt in case that's of interest.  Similarly, if someone drops again, it retains their old reentry_dt.

Is this data we need?  If not, I'll clear them.  If so, we'll modify the code for #77.

**Comment by rpardee** [comment]
What's unexpected for me (and I may just misunderstand the drop function) is that practices get a value in drop_reentry_dt when dropping out for the first time.  The logic I'm using to decide which rows to gray out on that view is:

  ::turn box gray:: if prac.drop_dt and not prac.drop_reentry_dt

So if they're dropped out & have a non-null drop_dt, they're dropped & show as gray.  But if someone thereafter re-enters them, they get a value in drop_reentry_dt and that if statement returns false, so they come out of gray-land.

You buy that?

**Comment by seemack** [comment]
I'm leaning toward using
` if !prac.active`
instead of
`if prac.drop_dt and not prac.drop_reentry_dt`
so we can retain the dates & if practices are ever made inactive for any other reason, they'll be de-emphasized as well.

**Comment by seemack** [comment]
I've also altered the sort order so inactive practices fall to the bottom of the list.  In coach_practices_controller.rb

```
  def list
    @coach = Partner.find(params[:id])
    @practices = policy_scope(Practice).where(coach_id: @coach.id).order(active: :desc, name: :asc)
  end
```

**Comment by rpardee** [comment]
Nice!

**Comment by seemack** [comment]
Feedback from Qualis suggests that they'd prefer the columns remain sortable rather than putting dropped practices at the bottom of the list.  I'll try to do both - though I was unsuccessful last time - but will prioritize sort over order if necessary.
