### ISSUE TITLE
2 practices have practice id's that dont look like they were enrolled

### ISSUE THREAD

**Issue by squabwrangler** [seemack/healthy-hearts-northwest-dev#86]
4J Wellness
Pine Meadows Family medicine

**Comment by squabwrangler** [comment]
Elena to confirm with Caitlin about these practices (that they were entered in error)

**Comment by kuoxes1** [comment]
These were never enrolled so should not have a practice ID.

**Comment by kuoxes1** [comment]
Confirmed with Caitlin that both these practices refused so shouldn't be "Dropped" we should remove their study IDS from the database

**Comment by seemack** [comment]
Study IDs 21110 & 21217 have been removed.
