### ISSUE TITLE
PDSAs not forwarding to next visits properly and so not displaying on the table on the Coach Practice page

### ISSUE THREAD

**Issue by squabwrangler** [seemack/healthy-hearts-northwest-dev#88]

**Comment by seemack** [comment]
71 PDSAs have a blank test status.  Although all PDSAs from the last visit are displayed, only adopted & abandoned PDSAs from prior visits are displayed.  The 02.23.2016 visit had a PDSA with no status type - although the comment says it's in planning - and therefore doesn't display.

Even if that PDSA *did* have a status of "planning" it wouldn't display.  Similarly, the 03.22.2016 visit has a PDSA with a "continuing testing" status that is not set to display.

This is working as intended.  Should we intend something different?

**Comment by squabwrangler** [comment]
Beth Sommers reports that when she enters a status of planning for a PDSA cycle, it does not show up in the next visit as does a PDSA marked continuing testing, but it should.  

Regarding the PDSA table on the coach practice page, we should discuss further with Nicole, but it sounds like if we could get all adopted and abandoned cycles to show up in the table at the bottom (regardless of date) and all continuing testing and planning cycles to show up at the top (from newest to oldest), that would be preferred.  Nicole, do you agree?

**Comment by kuoxes1** [comment]
Chris will need to write code to pull the prior nonHIT PDSA not just any old PDSA all the time into current activity.

**Comment by kuoxes1** [comment]
Chris needs to check that the table sorting: 
at the top:  most recent PDSA cycle that's in planning OR continuing testing phase.  
At the bottom: adopted or abandoned PDSAS

PLanning/continuing PDSAS need to pull into the next required contact (anything but HIT)

**Comment by seemack** [comment]
PDSAs are no longer ever associated with HIT or ad-hoc visits.  The proper PDSAs from required visits are being carried forward.  And the sort order is changed.  For simplicity, I'm pulling all the PDSAs from the most recent visit (in no particular order), followed by historical adopted/abandoned PDSAs.  The order of PDSAs from the most recent visit is a little complicated (meaning programmer time + slower web page response), so if this is important, let's talk about that.

**Comment by seemack** [comment]
Original title of this issue for posterity sake:
Lower Columbia PDSA not in the table on the practice page (dated: 02.23.2016)

**Comment by seemack** [comment]
Tested and awaiting new complaints.  :)
