### ISSUE TITLE
There are numerous practices that are Enrolled = Yes, not dropped (Date Dropped is null) and yet don't have Coaches assigned

### ISSUE THREAD

**Issue by rpardee** [seemack/healthy-hearts-northwest-dev#89]
The practices in the spreadsheet Elena sent for #85 that had no drop dates were problematic in that they all showed as Enrolled = Yes, were not dropped from the project (or, their values in drop_dt were all null) and yet had no coach assigned.

Looking today, all but one of the 7 practices in Elena's original spreadsheet are now marked as Enrolled = No, so I don't think those are problematic any more (is that right?).  But when I filter a new practice export on those conditions, I get a list of 9 such practices.  They are:

21146
32049
32071
32072
32073
32074
32075
32273
32379

I'll send Elena a spreadsheet w/full details on these to make it easy to (dis)confirm these are problematic & follow up w/managers to see if they've been overlooked, or should be marked dropped or what.

**Comment by squabwrangler** [comment]
Elena is working on this with the managers to get this handled.
