### ISSUE TITLE
Intervention arm

### ISSUE THREAD

**Issue by kuoxes1** [seemack/healthy-hearts-northwest-dev#95]
Add two topics to the check boxes:
1.  discussed site visits enhanced intervention
2.  discussed CVRC enhanced Intervention 

Needs to be ready by July 15

**Comment by squabwrangler** [comment]
Elena to ask Nicole where this should go in the topics section.  Tentatively under "Other" so that it stands out as a change. Words to include:  Site Visit  or CV Risk

**Comment by kuoxes1** [comment]
This is solidly going into "other" and needs to get done ASAP.

**Comment by seemack** [comment]
Added to IVContacts.  Ready for testing in dev.
