### ISSUE TITLE
Add PDSAs to ad-hoc contacts

### ISSUE THREAD

**Issue by seemack** [seemack/healthy-hearts-northwest-dev#98]
From Carolyn Brill:

> I went to Smokey Point and met with the provider for the Q2 required onsite visit
> In the same month I went back and we added another PDSA.
> Since I had to document it as a AdHOC visit, there was no ability to record the 2nd  PDSA.
>
> I went back into the previous Q2 required onsite visit and added the PDSA so it would be
> documented.
>
>I think we should add the PDSA to all visit types or give some instructions on this moving forward.
> I am starting to receive questions about documenting PDSA for AdHOC visits from others also.

In the email thread, we've talked about making this a training issue.  Another option is to add PDSAs to ad-hoc visits.  I like that option because coaches won't have to remember to go into a previous visit to populate the data.  OTOH, if it's not going to be used frequently, it'll just be more junk for the majority of coaches to scroll past.

Semi-related to Issue #94 - do we want to add additional (possibly rarely used) data to ad hoc visits, or do we want to train users to edit a previous visit, and possibly enter the date of the interaction that corresponds to the additional data?

**Comment by vanborkulo** [comment]
I think we add it to the adhoc visits with an 'OPTIONAL' notation.  I would add it after the comments section, so they don't even have to scroll through it unless they have one to include.

**Comment by kuoxes1** [comment]
We think this is a training issue.  
1.  Go back into the previous visit and document there if it's really important
2.  Wait until the next required contact and you will be able to document at that time in the new visit

Leah will email Michael, Nicole, Allen, Elena to see if the date matters and if this solution is ok or if we need to consider adding PDSA cycle to ad hoc.  Keep in mind that if we add PDS to adhoc ,then it will mess with the flag system, it will mess with how PDSAs forward from visit to visit (which is why Chris and Elena don't support adding).

**Comment by ltuz** [comment]
From: Van Borkulo, Nicole 

I think documenting either way is fine. Content is more important than the specific date discussed.

On Jun 15, 2016, at 4:32 PM, Tuzzio, Leah <tuzzio.l@ghc.org> wrote:
Hi Nicole and Michael –
We have built a lot of ways in the database for coaches to document a required visits, adhoc visits and HIT visits each having different information available (e.g., QICA only shows up twice). There was a coach request to make PDSAs available at ad-hoc visits but this could throw off some of the programming missing data flags, yet it is possible (everything is generally possible). 
We haven’t heard that it is too common for a PDSA to be discussed at an ad hoc visit/call, so the database team proposes that the solution is a training issue unless we need to know the exact date a PDSA was discussed. If an estimated date is ok, we propose the coach should…

1. Go back into the previous visit and document the PDSA within that visit 
2. Or, wait until the next required contact and the coach will be able to document at that time in the new visit
Thanks for confirming!
